### ISSUE TITLE
ValueError: too many attachments

### ISSUE THREAD

**Issue by toxicrecker** [miguelgrinberg/Flask-SocketIO#1526] opened 2021-04-18 14:23 UTC
why is this error being raised
![](https://cdn.yajtpg.xyz/yajtpg-cdn/Code_PsL58UfEkB.png)

**Comment by IvanHahan** [comment] 2021-04-18 15:22
I have this error in unit tests when I try to connect to a room using `test_client.connect('room_name')`

**Comment by dwolff** [comment] 2021-04-18 15:23
@miguelgrinberg I believe this is related to https://github.com/miguelgrinberg/python-socketio/issues/675, right?

**Comment by miguelgrinberg** [comment] 2021-04-18 15:34
Yes, I apologize for that regression. It is fixed now. Please upgrade python-engineio to the 5.2.1 release to get the fix.

**Comment by dwolff** [comment] 2021-04-18 15:40
> Yes, I apologize for that regression. It is fixed now. Please upgrade python-engineio to the 5.2.1 release to get the fix.

Thank you!
By the way: on my project dependencies (pyproject.toml) I don't import the python-engineio specifically, it looks like it's imported by the dependencies set by Flask-socketIO. Is there something you need to do on your side for that process to work properly?

**Comment by miguelgrinberg** [comment] 2021-04-18 15:48
@dwolff I'm not sure what mechanism you use to install your dependencies, but if you only have your first-level dependencies in your pyproject.toml file and you don't have either a requirements.txt file or something similar such as a lock file listing every single dependency with its version, then you don't have a way to create an environment that is repeatable, which sometimes can be a problem.

**Comment by dwolff** [comment] 2021-04-18 15:50
> @dwolff I'm not sure what mechanism you use to install your dependencies, but if you only have your first-level dependencies in your pyproject.toml file and you don't have either a requirements.txt file or something similar such as a lock file listing every single dependency with its version, then you don't have a way to create an environment that is repeatable, which sometimes can be a problem.

I'm using poetry, and yes, you are absolutely right: the dependencies kind of "fix themselves" =) 
Thanks again for the prompt response!

**Comment by toxicrecker** [comment] 2021-04-19 01:51
> Yes, I apologize for that regression. It is fixed now. Please upgrade python-engineio to the 5.2.1 release to get the fix.

The latest python-engineio version available on pypi is 4.1.0

**Comment by miguelgrinberg** [comment] 2021-04-19 09:10
Sorry, yes, it's python-socketio 5.2.1.

**Closed** 2021-06-27 19:39 UTC
