### ISSUE TITLE
Flask-SocketIO doesn't work with eventlet

### ISSUE THREAD

**Issue by xelhark** [miguelgrinberg/Flask-SocketIO#255] opened 2016-04-19 09:06 UTC
As soon as I install eventlet, my app stops working.
I can still see logs and incoming connections, but I stop receiving messages and events from the client.

I reproduced this with the following code:

```
from flask import Flask
from flask_socketio import SocketIO, emit

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
app.config['DEBUG'] = True
socketio = SocketIO(app)


@app.route('/')
def index():
    return "Hello"


@socketio.on('message')
def test_message(message):
    print "Received {}".format(message)
    emit("echo", message)


if __name__ == '__main__':
    socketio.run(app)
```

No changes in my client that just sends a "message" event and listens to "echo" events.

my pip-freeze:

```
eventlet==0.18.4
Flask==0.10.1
Flask-SocketIO==2.2
greenlet==0.4.9
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
python-engineio==0.9.0
python-socketio==1.2
six==1.10.0
Werkzeug==0.11.8
wheel==0.24.0
```

If I uninstall eventlet (pip uninstall eventlet) everything works fine.
Is this some versioning problem?
I couldn't find anything like this online.

**Comment by miguelgrinberg** [comment] 2016-04-19 14:14
What's your client like?

**Comment by PierrePaul** [comment] 2016-04-21 16:31
Make sure the ```gevent``` and ```gevent-socketio``` packages are not installed. [Engineio](https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/server.py#L86) will always try ```eventlet``` first and you will get issues if ```gevent``` is already installed.

See the [docs](https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/server.py#L86) for a little bit more details about eventlet/gevent.

**Comment by ocschwar** [comment] 2016-05-06 20:41
Could I call your attention to [this issue for socketio-client?](https://github.com/invisibleroads/socketIO-client/issues/116) 

The problem is that for some reason I could not diagnose, the background_task for sending packets out doesn't get started for a socket. So a queue.join() call deadlocks and the server does not receive messages from the client. 

A fix is needed in some combination of flask-socketio, python-engineio and socket-client, though  I remain mystified as to why the JS Socketio client does not cause this deadlock.

**Comment by miguelgrinberg** [comment] 2016-05-10 17:10
I think I need some help in running the code and getting it to deadlock. I was able to start the server, but then when I run the client there is a short exchange and the client exits.

**Comment by miguelgrinberg** [comment] 2016-10-09 21:11
@harsha-kadekar do you have a complete application I can use to reproduce the issue?

**Comment by harsha-kadekar** [comment] 2016-10-10 07:13
[](https://github.com/harsha-kadekar/Chitralochana/tree/master/Chitralochana_app)
I am developing this, where I have used socket for communication from backend to frontend. 
1. In file Twitter.py ([](https://github.com/harsha-kadekar/Chitralochana/blob/master/Chitralochana_app/app/twitter.py)), it forms a json data and sends it using this line socketIO.emit('stats', value, namespace='/analyze')
2. In communication.js ([](https://github.com/harsha-kadekar/Chitralochana/blob/master/Chitralochana_app/app/static/js/communication.js)) file, it uses socket.on('stats', function(data){}); to read the sent data.

@miguelgrinberg Not sure this is helpful or not....

**Comment by miguelgrinberg** [comment] 2016-10-10 16:53
@harsha-kadekar are you monkey patching the python standard library when you use eventlet? That's probably required in your case, given the dependencies that you use.

**Comment by harsha-kadekar** [comment] 2016-10-10 17:31
I have not done it. Let me try it and will get back to you once tested it.

**Comment by BrandonJoffe** [comment] 2016-10-10 18:03
@miguelgrinberg I'm also having the same problem I just tried monkey patching with:
#########
import eventlet
eventlet.monkey_patch()
############
....
socketio.run(app, host='0.0.0.0', debug = False, use_reloader=False)

I got the following error:

 File "/usr/lib/python2.7/dist-packages/numexpr/expressions.py", line 64, in __init__
    raise SystemError('__init__ called too many times')
SystemError: __init__ called too many times

Any help would be great, my project can be found here: https://github.com/BrandonJoffe/home_surveillance

**Comment by miguelgrinberg** [comment] 2016-10-10 20:42
@BrandonJoffe Unfortunately this appears to be a limitation of the numexpr package. There is an open bug for this error: https://github.com/pydata/numexpr/issues/118.

**Comment by BrandonJoffe** [comment] 2016-10-10 21:01
Thanks @miguelgrinberg  I'm still relatively new to Flask and I'm looking to deploy a Flask-SocketIO server. I just tried gevent on WGSI which gave me the same issues. I'm assuming this is a compatibility issue. Do you recommend I try Gunicorn and Gevent? Any pointers in the right direction will be incredibly helpful.

Thanks again.

**Comment by miguelgrinberg** [comment] 2016-10-10 21:05
My guess is that eventlet and gevent are going to be incompatible with numexpr in the same way, regardless of what web server you use. If you can't find a replacement for numexpr that works with green threads, then you can use Flask-SocketIO with the Flask development server, which does not require any external async frameworks. The disadvantage is that there is only long polling support in this mode, but to your application on the server and the client there should not be any difference other than performance, since this is all handled internally in a transparent way.

**Comment by BrandonJoffe** [comment] 2016-10-10 21:09
Ok I guess long polling will have to do for now, thanks.

**Comment by miguelgrinberg** [comment] 2017-03-17 19:10
Closing due to inactivity. Please reopen if the problem still exists.

**Closed by miguelgrinberg** 2017-03-17 19:10 UTC

**Comment by ColdHeat** [comment] 2017-05-08 07:30
After running `pip install eventlet` I get 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 261, in handle_request
    environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 89, in handle_get_request
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 136, in _upgrade_websocket
    return ws(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/async_eventlet.py", line 11, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
```

Is there something I'm not getting here?

**Comment by Joshua-Swain** [comment] 2019-07-31 21:37
I'm still pretty stuck on this too, using a small test app running in Docker. I've tried adding `async_mode='eventlet'` to the socketio.run() line, and that sometimes helped. But then when I removed that argument, the `RuntimeError: You need to use the eventlet server` would still not show up. It seems like the suggested solution is to use `socketio.run(app)`, but I'm already doing that.

I've looked at several related issues on this repository like 257, 279, 649, but I'm still on this bug


Here's my flask app (`partyproject.py`)
```from flask import Flask
import eventlet
from flask_socketio import SocketIO

app = Flask(__name__)
socketio = SocketIO(app)

@app.route("/")
def hello():
    return "<h1 style='color:blue'>So I heard there was a thing happening... </h1>"

if __name__ == '__main__':
    socketio.run(app)
```
Here's `wsgi.py`:
```from partyproject import app, socketio

if __name__ == '__main__':
    socketio.run(app)
```
Here's my `Dockerfile`:
```
FROM ubuntu:16.04

COPY . /home
WORKDIR /home

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get update -y && \
    apt-get -y upgrade && \
    apt-get -y install python3-pip python3-dev build-essential \
    libssl-dev libffi-dev python3-setuptools openssh-server docker.io && \
    pip3 install uwsgi flask flask-socketio==3.0.1 wheel eventlet==0.23.0 \
        flask-socketio==3.0.1

EXPOSE 5000
EXPOSE 80

COPY partyproject /etc/nginc/sites-available/partyproject

CMD ["uwsgi", "--socket", "0.0.0.0:5000", "--protocol=http", "-w", "wsgi:app"]
```

**Comment by miguelgrinberg** [comment] 2019-07-31 22:24
@Joshua-Swain you are using uWSGI, which as far as I know is incompatible with eventlet. Have you seen the [documentation](https://flask-socketio.readthedocs.io/en/latest/#deployment)? I show all the configurations that I have personally tested and found to work. I suggest you use one of those.

**Comment by Joshua-Swain** [comment] 2019-08-01 14:28
That explains it. Yeah I used the configuration suggested for uWSGI and the app runs now. Thanks for the help!

**Comment by MarianoDel** [comment] 2020-07-09 21:37
Hi Miguel, I'm using socketio to send some audio packets. All works just fine but I'm using the development server.
As soon as installed eventlet the audio packets aren't working any more, other socketio packets are fine, only audio is the problem.
Some times I get this message in the browser:
WebSocket connection to 'ws://192.168.0.103:5000/socket.io/?EIO=3&transport=websocket&sid=370d67a8086e4e77a34bc8e1356aff8f' failed: Received a broken close frame containing invalid UTF-8.

If I uninstall eventlet all works again!

**Comment by miguelgrinberg** [comment] 2020-07-10 08:13
@MarianoDel hard to comment on this without details. Do you think you can create a small example app that I can try here to reproduce the issue? If you can, please file a separate issue and provide the code.

**Comment by MarianoDel** [comment] 2020-07-10 21:23
Hi Miguel, I'm think I forget mokey paching, will try this and get a feddbak.Thanks for your answer!!!
Mariano E. Deleu marianodeleu@yahoo.com.ar 

    El viernes, 10 de julio de 2020 05:14:02 ART, Miguel Grinberg <notifications@github.com> escribió:  
 
 


@MarianoDel hard to comment on this without details. Do you think you can create a small example app that I can try here to reproduce the issue? If you can, please file a separate issue and provide the code.

**Comment by stefets** [comment] 2021-11-26 03:43
Hi, sorry to reopent this discussion, and I have no technical details but I am creating a simple application and it works very flawless in development mode it's lightning fast and all the websockets logics works.  Repo is : /stefets/flaskdings

Next step in my process is to go PRE-PROD; I have pip install eventlet in my virtual env and when I start my app in 'production mode' the websocket protocol don't work.

Do I have to configure eventlet ? Do I have to put some code in the io consructor ? 

Any advice are welcome!

**Comment by miguelgrinberg** [comment] 2021-11-26 08:20
@stefets this type of problem is usually caused by applications that do things that are incompatible with eventlet, and it is not an issue with this package or with eventlet itself.

**Comment by stefets** [comment] 2021-11-26 13:13
Ok  My application just do a little usage of websocket, couple of socket.on and couple of socket.emit. I will try another service than this eventlet. By  the ways @miguelgrinberg your Flask-SocketIO is just awesome! 
Thanks!

**Comment by miguelgrinberg** [comment] 2021-11-26 14:48
@stefets Have you read eventlet's documentation? If you are going to use it, you should familiarize yourself with what works and what doesn't. In particular mixing threads with eventlet is tricky, because eventlet provides its own concurrency model that is single-threaded. For some applications the monkey patching option of eventlet helps, as mentioned above in this issue.

**Comment by stefets** [comment] 2021-11-26 14:56
@miguelgrinberg Thanks, I will take a look; I'm new to websocket and eventlet and I will try the monkey thing... It's possible for me to modifiy my logic a little bit to make it works with eventlet without the other thread. Thanks for your help!
