### ISSUE TITLE
Connection disconnection produces exception in the server.

### ISSUE THREAD

**Issue by fake-name** [miguelgrinberg/Flask-SocketIO#184] opened 2015-12-16 20:13 UTC
Basically, I have a minimal app, with an absolutely minimal page:

```
	<script src="/static/js/socket.io.js"></script>
	<script>
		var socket = io();
	</script>
``` 
(literally, that's it).

Every time the client disconnects, the server throws an error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/eventlet/wsgi.py", line 470, in handle_one_response
    for data in result:
TypeError: 'NoneType' object is not iterable

```

**Comment by fake-name** [comment] 2015-12-16 20:17
This appears to be happening *after* the disconnect calls (if any) are invoked, e.g. 

```
@socketio.on('disconnect')
def test_disconnect():
	print('Client disconnected')
```
successfully prints 'Client disconnected', so it's not a game-breaking issue, but it is annoying.

**Comment by miguelgrinberg** [comment] 2015-12-17 01:30
Are you using latest versions of all dependencies? I recall this happening a while ago because the response to the WebSocket request was incorrect, but this is already fixed. Upgrade flask-socketio, python-socketio and python-engineio and let me know if you still get the error.

**Comment by fake-name** [comment] 2015-12-17 02:04
I literally installed all the dependencies this afternoon, so unless the dependency packages in PyPi is out of date, yes, I should be on the most recent version.

**Comment by miguelgrinberg** [comment] 2015-12-17 03:53
And you trigger a disconnect event by closing the browser window? Or in a different way?

**Comment by fake-name** [comment] 2015-12-17 04:06
Yep.

**Comment by fake-name** [comment] 2015-12-17 18:33
Installed package versions:

```
durr@build3:/media/sf_Code/openvna/WebVna$ pip3 freeze

Flask-SocketIO==1.2
python-socketio==0.8.1
python-engineio==0.8.3

```

**Comment by miguelgrinberg** [comment] 2015-12-17 23:31
Okay, thanks for all the details. I'll see if I can reproduce this here.

**Comment by fake-name** [comment] 2015-12-17 23:47
No, I pretty much just started hacking on my own projects. I'll give it a spin and see. Hold on.

**Comment by miguelgrinberg** [comment] 2015-12-17 23:48
Or else if you can share your project, that'll help me see the same thing you are seeing.

**Comment by fake-name** [comment] 2015-12-17 23:55
Yep, same behaviour with the demo project.

I did change the initialization line from the demo project: 

```
if __name__ == '__main__':
    socketio.run(app, host='0.0.0.0')

```

This is because my test-environment is a linux VM, but I'm connecting to it from windows. The default is to only listen on localhost, which means I can't access the served content except from inside the VM (which doesn't even have a browser installed).

The other minor thing I notice is that Ctrl+C usually doesn't kill the application (mine, and the demo), it just prints `^Cwsgi exiting`, and then continues on running and serving HTML content (though websocket connections then fail to connect). It does that until I get irritable and hit Ctrl+C a few more times and force-kill it.

**Comment by fake-name** [comment] 2015-12-17 23:59
Incidentally, thanks for being so responsive! Projects like this are why I like working on open source stuff.

**Comment by miguelgrinberg** [comment] 2015-12-18 00:06
No problem, I really really hate it when someone finds a bug in my code ;-)

I'll have time tonight to look at this, I'll write an update once I get a chance to test.

**Comment by fake-name** [comment] 2015-12-18 00:14
No hurry, it's annoying, not a gamebreaker. 

It's not like the crap I'm working on doesn't spew hundreds of errors to the console when it dies anyways (whoo! Custom hardware! Custom UDP-based protocols! What am I doing with my life....).

**Comment by miguelgrinberg** [comment] 2015-12-18 07:39
Please upgrade package python-engineio. A pull request that I merged a couple days ago caused the regression you reported (error `TypeError: 'NoneType' object is not iterable`). I removed the PR in version 0.8.4 of this package, until I figure out exactly what went wrong.

As far as stopping a process with Ctrl-C, it is kind of a mess, as I suspect. For eventlet it appears you have to do it twice. First time it prints the "wsgi exiting" message, and the second time kills it for good. With Werkzeug I've got a few successful stops, but more often than not I've got a hang, which I suspect is a bug in the stopping of the server when it is running in threaded mode (something that Flask never does, but it is sadly required to run Socket.IO). Feel free to log bugs for these, I don't consider them a top priority, they seem like issues on the servers.

**Comment by fake-name** [comment] 2015-12-22 00:34
That rollback fixes the error message.

Do you want me to leave this open until you solve the merge issue, or what? Feel free to do whatever makes your life easier.

**Comment by fake-name** [comment] 2015-12-22 00:40
Wait, correction. That patch doesn't cause the issue at all, it just causes it to happen somewhere else:

If I time the page-close correctly (when It's in a data transaction? I dunno about the websockets internals):

```
Client disconnected
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/eventlet/wsgi.py", line 483, in handle_one_response
    write(b''.join(towrite))
  File "/usr/local/lib/python3.4/dist-packages/eventlet/wsgi.py", line 426, in write
    _writelines(towrite)
  File "/usr/lib/python3.4/socket.py", line 394, in write
    return self._sock.send(b)
  File "/usr/local/lib/python3.4/dist-packages/eventlet/greenio/base.py", line 359, in send
    total_sent += fd.send(data[total_sent:], flags)
BrokenPipeError: [Errno 32] Broken pipe
```

Emitted *immediately* upon page-close.

If you don't time it:
```
Client disconnected
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/eventlet/wsgi.py", line 483, in handle_one_response
    write(b''.join(towrite))
  File "/usr/local/lib/python3.4/dist-packages/eventlet/wsgi.py", line 426, in write
    _writelines(towrite)
  File "/usr/lib/python3.4/socket.py", line 394, in write
    return self._sock.send(b)
  File "/usr/local/lib/python3.4/dist-packages/eventlet/greenio/base.py", line 359, in send
    total_sent += fd.send(data[total_sent:], flags)
BrokenPipeError: [Errno 32] Broken pipe
```

Is emitted a period of time after the connecting tab is closed (30 or 60 seconds). Note that the "GET xxx" log message is printed *after* the connection times out, apparently (not sure if it's relevant).

**Comment by miguelgrinberg** [comment] 2015-12-22 03:22
These are nicer errors, in my opinion. The error that you reported was caused by this extension, because it was returning an invalid response back to the WSGI framework.

These other errors are simply caused by the WSGI framework losing the connection, without involvement of the socketio code (as far as I can see, I need to verify this claim). The broken pipe and connection reset errors are actually expected to see in these situation where one of the parties drops off unexpectedly, and it is the job of the WSGI framework to handle those. In some places these are handled (see the usages of [this symbol](https://github.com/Cue/eventlet/blob/master/eventlet/wsgi.py#L40), for example), and I suspect some other places need to handle these as well.

**Comment by fake-name** [comment] 2015-12-22 21:06
Well, it seems that the higher-level interface can detect the dropped connection without resorting to timeouts (or else how would it error immediately, in the first case), so it seems that it should be possible to have to tear-down the session gracefully.

I cannot see having a remote client drop with a tab-close as being in any way unusual enough that it shouldn't be handled gracefully. Otherwise, you clutter up any logging systems you have with huge numbers of spurious and harmless errors.

**Comment by jextrevor** [comment] 2015-12-24 01:58
I'm getting this error too

**Comment by artemiy-rodionov** [comment] 2015-12-31 09:59
+1 Get this error on every client disconnect

**Comment by dimitrovs** [comment] 2016-02-02 03:35
Would this be related?

` Traceback (most recent call last):
flask_1 |   File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 465, in handle_one_response
flask_1 |     result = self.application(self.environ, start_response)
flask_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
flask_1 |     return self.wsgi_app(environ, start_response)
flask_1 |   File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 37, in __call__
flask_1 |     start_response)
flask_1 |   File "/usr/local/lib/python2.7/dist-packages/engineio/middleware.py", line 47, in __call__
flask_1 |     return self.engineio_app.handle_request(environ, start_response)
flask_1 |   File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 303, in handle_request
flask_1 |     return self.eio.handle_request(environ, start_response)
flask_1 |   File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 232, in handle_request
flask_1 |     del self.sockets[sid]
flask_1 | KeyError: `'202368e38f194fe48645141a45c64c22'``

**Comment by miguelgrinberg** [comment] 2016-03-24 17:33
@dimitrovs the error you reported has been already addressed.

#160 captures the benign errors from web servers when the client goes away.

**Closed by miguelgrinberg** 2016-03-24 17:33 UTC
Labels: bug
