### ISSUE TITLE
Handling preflight requests with extraHeaders?

### ISSUE THREAD

**Issue by fgortiz** [miguelgrinberg/Flask-SocketIO#630] opened 2018-02-02 20:17 UTC
Hi,

Whenever I try to connect to my socket.io server using the extraHeaders option for the polling transport, I can't seem to be able to connect; I always get a 405 - METHOD NOT FOUND  error in the preflight request that I don't get without.

Official policy appears to be [Adding a method for preflight requests](https://github.com/socketio/socket.io-client/issues/1140), but I can't quite find something similar in the flask-socket.io docs.

**Comment by miguelgrinberg** [comment] 2018-02-02 23:14
Flask-SocketIO should, in theory, handle the CORS preflight requests already. Can you look in the network tab of your browser's console to see exactly what request the browser is sending the comes back as a 405?

**Comment by fgortiz** [comment] 2018-02-03 14:49
Thanks!

**Comment by TheNewToddler** [comment] 2018-03-05 09:26
I had the same issue. I just installed eventlet and then things worked. Not sure how it works but thought I would share.

**Comment by corescript** [comment] 2018-03-19 09:44
**For CORS Use**
{
handlePreflightRequest: function (req, res) {
var headers = {
'Access-Control-Allow-Headers': 'Content-Type, Authorization',
'Access-Control-Allow-Origin': req.headers.origin ,
'Access-Control-Allow-Credentials': true
};
res.writeHead(200, headers);
res.end();
}
}

**Comment by fgortiz** [comment] 2018-03-19 19:28
Any update?

**Comment by 90K2** [comment] 2018-04-20 19:44
Agree that when I use custom headers, browser sending OPTIONS request and gettin 405 Not allowed back.

**Comment by miguelgrinberg** [comment] 2018-04-23 02:40
@fgortiz @90K2 can I ask you to install the master branch for [python-engineio](https://github.com/miguelgrinberg/python-engineio) and test the CORS preflight request support? If you confirm that it works, I'll cut a new release. Thanks!

**Comment by 90K2** [comment] 2018-04-23 07:59
@miguelgrinberg it's looks like a magic but browser is not asking OPTIONS anymore and all requests are processing correct. Seems that it works ^_^

**Comment by miguelgrinberg** [comment] 2018-04-23 16:52
Right, that is why I have never seen this problem before. I have never seen `OPTIONS` requests being sent for Socket.IO. Not sure what is the proper environment to reproduce this, but if you find out let me know.

**Comment by 90K2** [comment] 2018-04-24 02:10
Hmm I thinks it's easy to reproduce. 
My use case was like this: I have added custom header `X-Auth-Access-Token` on front app due to authorization and with other headers this react app going to socketio server. 

That's all, this custom header provoked browser to enable CORS and making OPTIONS preflight requests for each request to backend.

**Comment by miguelgrinberg** [comment] 2018-04-27 04:01
This fix is now released with python-engineio v2.1.0.

**Comment by 3mp3ri0r** [comment] 2018-05-11 06:54
Hi there I still got the issue. socketio client ask for preflight when connecting using polling. This is server stack I use:

> python-engineio==2.1.0
python-socketio==1.9.0

Any idea to solve this issue?

**Comment by miguelgrinberg** [comment] 2018-05-11 11:50
Oh, sorry about that, I missed declaring the method from the sanic side. I implemented the support for it, but sanic is not configured to dispatch that method. I need to fix this.

**Comment by miguelgrinberg** [comment] 2018-06-15 06:31
This is fixed in release 2.1.1 of python-engineio.

**Closed by miguelgrinberg** 2018-06-15 06:31 UTC
Labels: bug

**Comment by DavidLeibs** [comment] 2020-09-21 21:04
I am trying to run the basic flask-socketio example on macOS Catalina. I get a 405 Method Not Allowed error on Safari. It works on Chrome.  If I disable cross origin restrictions on Safari it works.  What is the right setup for app.py so that I might run without having to disable Safari's cross origin restriction setting?  I suspect I am just too new to Flask and Flask-SocketIO to do what must be obvious to someone with more.  I have found the advice I find on various stack exchange threads to not be helpful.

**Comment by miguelgrinberg** [comment] 2020-09-21 21:36
@DavidLeibs Can you provide more details on this error? What is the attempted method? What URL? This information should be available from the developer console.

**Comment by DavidLeibs** [comment] 2020-09-21 22:25
It seems like something wacky with Safari. It goes bad right at the beginning When I load the index.html page the developer console shows:

Cross-origin redirection to https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js denied by Cross-Origin Resource Sharing policy: Origin http://localhost:5050 is not allowed by Access-Control-Allow-Origin.

Cross-origin script load denied by Cross-Origin Resource Sharing policy.

ReferenceError: Can't find variable: io

Failed to load resource: Cross-origin redirection to https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js denied by Cross-Origin Resource Sharing policy: Origin http://localhost:5050 is not allowed by Access-Control-Allow-Origin.

This does not happen when I "Disable Cross-Origin Restrictions"

I do not see this with Chrome.

**Comment by miguelgrinberg** [comment] 2020-09-22 08:07
@DavidLeibs I don't know what is it specifically that your Safari does not like. When I request the socket.io.js URL it comes back with the correct CORS header that allows all origins.

![Screen Shot 2020-09-22 at 9 06 27 AM](https://user-images.githubusercontent.com/2715854/93857799-0fa46900-fcb3-11ea-9c17-2dcc6e1e33d7.png)

Do you get a different CORS header there?

**Comment by bluthen** [comment] 2020-09-22 14:32
It looks like it is Safari not liking cross-origin from http localhost to a remote https. I know safari is more picky about cors things. But from the message it seems like the problem begins with just loading socket.io.js in the browser and doesn't actually have anything to do with flask-socketio

**Comment by DavidLeibs** [comment] 2020-09-22 14:38
I safari 14.0 just does not seem to want to fetch jquery and socket.io with the script tags as you specified them. 

Changing the script tags to:

  <script src="//code.jquery.com/jquery-1.12.4.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js"></script>

works just fine (which is sad).

Here is a link to bugs.webkit.org that might go a little way in explaining what's going on.

     https://bugs.webkit.org/show_bug.cgi?id=171566

I had already just grabbed the javascript from Cloudflare and Jquery and put it on my development server and moved on but I hope that leaving this trail will help the next person that wants the example to work out of the box and also happens to be using Safari to thinking that they are going crazy. :-)

**Comment by tallPaul66** [comment] 2021-09-03 23:11
@DavidLeibs Thank you for posting the js code that works for Safari. I was having exactly the same issue you were (but I'm using Safari 14.1.2), and did not have the issue in Chrome. But I wanted you to know that your posting the solution here helped  me a lot, so I guess I was one of those "next person(s)" you intended to help, and indeed it did. Thanks!
