### ISSUE TITLE
Logging configuration ignored when running with SocketIO.

### ISSUE THREAD

**Issue by richburdon** [miguelgrinberg/Flask-SocketIO#134] opened 2015-09-05 03:53 UTC
I'm configuring custom handlers and formatters via:

    logging.config.dictConfig(yaml.load(open(self.config['LOG_CONFIG'])))

But the werkzeug HTTP logger doesn't respect these after running with SocketIO (see the 2 GET logs below). If I run the same server using the regular Flask.run then everything is OK.

    2015-09-04 23:45:41,942 [            root|main.py         :  77][INFO] ### DEVELOPMENT ###
    2015-09-04 23:45:48,106 [            root|main.py         : 189][INFO] Startup OK
    127.0.0.1 - - [2015-09-04 23:45:48] "GET / HTTP/1.1" 200 2898 0.035956
    127.0.0.1 - - [2015-09-04 23:45:48] "GET /css/main.css HTTP/1.1" 200 31259 0.015762
    2015-09-04 23:49:00,152 [oauth2client.uti|util.py         : 139][WARN] build() takes at most 2 positional arguments (3 given)
    127.0.0.1 - - [2015-09-04 23:49:01] "POST /data HTTP/1.1" 200 358 1.779027

Running without SocketIO:

    2015-09-04 23:51:55,471 [            root|main.py         : 189][INFO] Startup OK
    2015-09-04 23:51:55,485 [oauth2client.uti|util.py         : 139][WARN] build() takes at most 2 positional arguments (3 given)
    2015-09-04 23:51:57,343 [        werkzeug|_internal.py    :  87][INFO] 127.0.0.1 - - [04/Sep/2015     23:51:57] "POST /data HTTP/1.1" 200 -

**Comment by miguelgrinberg** [comment] 2015-09-05 04:21
What version of Flask-SocketIO are you using?

**Comment by richburdon** [comment] 2015-09-05 06:41
Flask-SocketIO (0.6.0)

**Comment by miguelgrinberg** [comment] 2015-09-05 20:49
Can you show me where in the application you configure logging? I wonder if it is done too late.

**Comment by richburdon** [comment] 2015-09-06 00:15
My simplified app structure is below. Just a note: if I switch the last line to just run Flask, then the logging works as expected.

    app = Flask(__name__,
        static_url_path='/res',
        static_folder='../resources',
        template_folder='templates')

    env = Environments(app)
    env.from_yaml(os.path.join(os.getcwd(), conf_yml))
    app.config['ENVIRONMENT'] = app.config['ENVIORNMENT']
    logging.config.dictConfig(yaml.load(open(app.config['LOG_CONFIG'])))

    socketio = SocketIO(app)

    socketio.run(app)          # This has problems with werkzeug logging
    app.run()                       # This works fine.

**Comment by miguelgrinberg** [comment] 2015-09-13 22:50
Could you try the 1.0a1 development release of Flask-SocketIO? Note that this version has substantial differences with the version you are using, so you may see other unrelated problems.

**Comment by richburdon** [comment] 2015-09-21 16:11
Thanks Miguel, yes that seems to be working.

When are you expecting to be out of alpha with 1.0?

**Comment by miguelgrinberg** [comment] 2015-09-21 20:14
I put out a beta release yesterday, 1.0b1. If no big issues happen with it I'll go ahead and release in a week or so.

**Comment by richburdon** [comment] 2015-09-22 00:47
Thanks for the quick response; while logging was resolved my JS client is having problems with the new version (below). Were there JS API changes with 1.0?

socket.io.min.js:2 Uncaught TypeError: Cannot read property 'onClose' of null

**Comment by richburdon** [comment] 2015-09-22 02:46
I updated my JS client version and now multiple errors on the server:

1). If I specify a callback, onError is called with the error below:
socketio.emit("E", response, namespace=self.namespace), callback=lambda: LOG.info('ACK'))

ERROR: 'Server' object has no attribute '_generate_ack_id'

I can comment this out as a work-around.

2). I'm now seeing FlaskLogin's @login_manager.user_loader being called on the receipt of inbound messages. This manifests in a server exception since my loader depends on a manager class bound to flask.g in the app's "before_app_request" callback. Clearly the socket isn't triggering the callback, but I think it's reasonable for FlaskLogin to expect that before_app_request has been called?

3). I sporadically get the following errors. These happen frequently, but I haven't been able to isolate them. Also the server fails to shut down often (running and stopping from my IDE, PyCharm); this never used to happen and now requires a kill from the command line (which is awkward).

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 58198)
----------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

**Comment by miguelgrinberg** [comment] 2015-09-22 05:15
Regarding this error:

> socket.io.min.js:2 Uncaught TypeError: Cannot read property 'onClose' of null

I quick search seems to suggest there is a problem in how you create the socket instance in the client. 

> ERROR: 'Server' object has no attribute '_generate_ack_id'

Wow, I'm surprised this one slipped, I'm missing some unit tests to exercise this. I need to fix it on my side. If you commented out the offending code, messages will get sent, but callbacks will not be invoked.

> I'm now seeing FlaskLogin's @login_manager.user_loader being called on the receipt of inbound messages.

Very odd. Are you using websocket or long-polling? Any chance you can put a breakpoint in your callback and generate a stack trace so that I can see who's making the call?

> error: [Errno 32] Broken pipe

This sometimes happens when you close a browser tab that has a long polling connection to the server. The server is just saying that the socket went away. These can be safely ignored, unless they happen under different conditions than what I just described.

**Comment by miguelgrinberg** [comment] 2015-09-22 05:46
@richburdon the `_generate_ack_id` error should be fixed now. You need to upgrade one of the dependencies to get the fix:

    pip install --upgrade python-socketio

**Comment by richburdon** [comment] 2015-09-22 13:25
1). I tested callbacks with the update and they are working. (Nice).
2). The FlaskLogin issue was a false alarm. My inbound socket message was triggering it through user code.
3). Re long polling -- unless that is automatically activated in DEBUG mode (?) then I'm not using it. It would be nice to be able to catch this and squash the error.

GL with getting out of beta. Looking forward to it. Thanks.

**Comment by miguelgrinberg** [comment] 2015-09-22 14:47
On #3, you should have eventlet or gevent and gevent-websocket installed in your virtual environment for websocket to be used. If you don't have any of these installed, then long-polling is the only mechanism that can be used. Also note that in the 1.0a1 release debug mode always used long-polling, but this limitation went away in 1.0b1.

**Comment by richburdon** [comment] 2015-09-22 21:27
OK. pip pulls in "gevent-websocket" as a dep of "Flask-SocketIO" so I've always had that. How do I know if I'm long polling?

1. I currently have some FlaskLogin configuration (database stuff) happening in Flask.before_first_request. Since sockets may now connect before there is any HTTP request, can you suggest a different hook for server startup tasks?

2. Another plea for the ability to catch the disconnect error (below); I have logging set-up so that exceptions trigger email alerts. I can config logging to ignore these, but then I may squash legitimate errors.

3. It's become cumbersome to restart the dev server (e.g., I'm using PyCharm). 50% chance of getting "Socket already bound" and sometimes 5 times in a row or requires a console kill. It really gets in the way of iterative development.

Neither of the above are critical obviously, but would be great if you'd consider them.


Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

**Comment by miguelgrinberg** [comment] 2015-09-27 02:38
> can you suggest a different hook for server startup tasks?

Do you have an application factory function? That would work as a place to do initialization tasks.

> Another plea for the ability to catch the disconnect error 

I think I need to understand this problem better. This exception is triggered as a result of a client going away and closing their side of the socket. From the stack trace, it appears you are using the threading mode, so this is likely the server trying to write a response on a socket that went away (let me know if I got this wrong).

Unfortunately this happens in the socket/wsgi side of things, this is not an application error. I may be able to catch these when using websocket because in that situation I have direct read/write access to the socket, but when using HTTP the reads and writes happen at the wsgi layer, outside of my control.

> 50% chance of getting "Socket already bound"

Which OS and which async mode are you using? I'll try to reproduce.

**Comment by ekw** [comment] 2015-10-03 18:59
Related to logging, when pass in "log_file" parameter to run() like so: 
socketio.run(app, log_file='/var/log/app-acccess.log')

The writes (by werkzeug/gevent?) to the log file do not get flushed until I kill the process with Ctrl-C.  The flask app.logger() writes are seen as soon as the call is made.  Is this expected?  I don't plan on using gunicorn or nginx, just plain socketio.run().

**Comment by miguelgrinberg** [comment] 2015-10-18 18:36
@ekw the `log_file` argument was available in the 0.x releases, as it was handled by gevent-socketio. In the 1.x releases it does not exist anymore. You can configure logging to a file passing arguments that are specific to the web server that you are using (gevent, eventlet or Werkzeug).

**Closed** 2016-03-24 17:21 UTC
Labels: bug

**Comment by j-walker23** [comment] 2016-09-04 22:49
@richburdon sorry this is a long time ago. But I am interested in how you are getting your logs to format the way you show. Can't get mine to work. Any chance you can show your log config yaml file?

**Comment by richburdon** [comment] 2016-09-05 03:55
hi john.
i move from flask to using various third-party push servies (Google GCM and
pusher.io) some time ago, so don't have an operational flask-socketio stack
at the moment.
rich
