### ISSUE TITLE
Error on connect: wss:// is not an accepted origin

### ISSUE THREAD

**Issue by ffleandro** [miguelgrinberg/Flask-SocketIO#1055] opened 2019-09-10 23:54 UTC
I'm experiencing the following error when connecting to `flask-socketio` using the swift client.
> Error: wss://myurl:port is not an accepted origin.

When connecting using the java client everything works correctly.

Using the following versions:
```
Name: Flask-SocketIO
Version: 4.2.1
---
Name: python-engineio
Version: 3.9.3
```

Rollbacked `python-engineio` to version `3.8.2` and `flask-socketio`  to version `4.2.1` and everything works correctly with both swift and java clients, so perhaps this has something to do with the new CORS improvements on latest versions.

**Comment by miguelgrinberg** [comment] 2019-09-11 08:01
Closing as a duplicate of https://github.com/miguelgrinberg/python-socketio/issues/351.

**Closed by miguelgrinberg** 2019-09-11 08:01 UTC

**Comment by ffleandro** [comment] 2019-09-11 11:37
Sorry, I was sure I had already posted it, but couldn't find where.
