### ISSUE TITLE
restricting access to socketio/client files with flask-socketio?

### ISSUE THREAD

**Issue by raheel4839** [miguelgrinberg/Flask-SocketIO#1229] opened 2020-04-02 07:46 UTC
Hi,

i am having a problem where i am able to download certain socketio files from my flask application.

i am initializing Socketio server with following call:
`SocketIO(app, async_mode=async_mode, message_queue='redis')`

sending a call to https://localhost:port/socket.io/ downloads a file with 'sid' and other information.

Similarly i am able to download different socketio files like : socket.io.tar.gz and socket.io.arj and other socketio compressed files by appending the names in the path. e.g. https://localhost:port/socket.io/socket.io.tar.gz gives me the file.

after searching alot about this issue, one thing i think can be helpful is setting serveClient=false as it is recommended in production environment. but i am unable find any information on how and where to set this parameter in case of python flask socketio.

So my question is how can we restrict access to these files? is there some socketio side configuration or some Content-Security-Policy i am missing.

I ll be grateful if someone can help with this issue.

Thanks

**Comment by miguelgrinberg** [comment] 2020-04-02 10:32
Closing as a duplicate of https://github.com/miguelgrinberg/python-socketio/issues/455. You are posting the same issue on multiple related repositories? What's the point in doing that?

**Closed by miguelgrinberg** 2020-04-02 10:32 UTC

**Comment by raheel4839** [comment] 2020-04-02 11:09
Sorry about that.... Later i thought, maybe this repository was more related to my question.

> Closing as a duplicate of [miguelgrinberg/python-socketio#455](https://github.com/miguelgrinberg/python-socketio/issues/455). You are posting the same issue on multiple related repositories? What's the point in doing that?
