### ISSUE TITLE
Why override `flask run`?

### ISSUE THREAD

**Issue by MaxNoe** [miguelgrinberg/Flask-SocketIO#713] opened 2018-06-01 07:24 UTC
This was really unexpected to me. Just having flask-socketio installed breaks `FLASK_DEBUG=true` because it overrides the `flask run` command.

Why is this done and is this really necessary?

**Comment by miguelgrinberg** [comment] 2018-06-01 17:49
It isn't supposed to break anything. Can you describe what is the problem that you found?

The reason `flask run` is overriden is that Flask-SocketIO tries to use a web server that supports WebSocket if available.

**Comment by MaxNoe** [comment] 2018-06-02 11:47
See https://github.com/pallets/flask/issues/2200

**Comment by miguelgrinberg** [comment] 2018-06-02 13:45
@MaxNoe I can't reproduce that error with latest versions of Flask and Flask-SocketIO and my own test application. Do you have a simple example I can try here, and the output of `pip freeze` in your virtual environment? I hope that should be enough for me to reproduce this problem.

**Comment by MaxNoe** [comment] 2018-06-03 20:40
```
$ pip freeze
click==6.7
ctools==1.3.0
Flask==1.0.2
Flask-SocketIO==3.0.0
gammalib==1.3.0
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
python-engineio==2.1.1
python-socketio==1.9.0
six==1.11.0
Werkzeug==0.14.1
```

Having this issue inside a minimal installation using pipenv and only flask and flask_socketio with the flask hello world app.

**Comment by miguelgrinberg** [comment] 2018-06-03 20:47
Oh, so you installed Flask-SocketIO in your virtualenv but are not using it in the application?

**Comment by MaxNoe** [comment] 2018-06-03 21:05
Yes

**Comment by MaxNoe** [comment] 2018-06-03 21:11
I ran into this, when I started a new Project and intstalled `flask_socketio` but wasn't using it yet.

**Comment by miguelgrinberg** [comment] 2018-06-03 21:54
Should be fixed in release 3.0.1.

**Comment by miguelgrinberg** [comment] 2018-09-12 22:32
This fix was undone, as it affects the operation of the reloader for normal apps. Will need to find a different way to address this problem.

**Comment by Kamforka** [comment] 2018-11-27 15:23
Have the same issue. It's quite unorthodox for a `pip install` to break my app :D

**Comment by miguelgrinberg** [comment] 2018-11-27 16:42
@Kamforka yes, I apologize for that. This used to work fine with Flask < 1.0 versions, but some changes that went into that release are incompatible with my solution.

**Comment by Kamforka** [comment] 2018-11-27 20:22
@miguelgrinberg is the fix in progress or you welcome contributors to sort it out?

**Comment by miguelgrinberg** [comment] 2018-11-27 20:23
This isn't at the top of my list at this time, given that it has a very easy workaround (i.e. uninstall Flask-SocketIO if you are not using it!). You are welcome to look into it.

**Comment by GlennG2012** [comment] 2019-01-16 01:10
Hey, I don't know if this helps. But rather than installing/uninstalling flask-socketio, place if __name__ == '__main__': socketio.run(app) on applications that uses it, and then app.run() on those that don't. rather than flask run, do 'python application.py' on terminal instead

**Comment by Kamforka** [comment] 2019-01-16 14:11
@GlennG2012 thanks for the suggestion, however our deployment relies on `flask run` and it was causing problem during the onboarding of `Flask-SocketIO` whereas on one branch we had an app without socketio and on an other we had with socketio but in the package was already installed in the virtual environment. Now that those branches without socketio are extinct it's not a huge deal any more, just inconvenient for a fresh start.

**Comment by miguelgrinberg** [comment] 2019-01-23 19:53
Starting with Flask-SocketIO 3.2.0 (just released), the `flask run` command can only be used with the threading mode. For all other async modes, the `socketio.run(app)` method should be used to start the server.

**Closed by miguelgrinberg** 2019-01-23 19:53 UTC
Labels: bug

**Comment by miguelgrinberg** [comment] 2019-01-24 18:33
@Kamforka that can all be done. What cannot be done easily is to pass through control from my modified run to the original run in the cases where this is necessary. I can't also automatically change my modified run function to match changes made to the Flask run command. When this happens my function breaks and I need to put out the fire. It brings me a lot of unhappiness, and all to support a way of starting the server that I don't even like.
