### ISSUE TITLE
Socket getting disconnected inexplicably/inconsistently

### ISSUE THREAD

**Issue by sandeepckeerthi** [miguelgrinberg/Flask-SocketIO#1135] opened 2019-12-24 18:04 UTC
Hi Miguel, 
We are using SocketIO to stream Twitter data (after due processing in a Spark layer) in order to stream the data to a browser. However, we notice that a disconnect event is getting fired (presently we are not sure if disconnect event is getting fired from client end or the server).

We have attached the server log file for your reference. You can see the log generated form our code at line no. 381. 

[server.log](https://github.com/miguelgrinberg/Flask-SocketIO/files/3998834/server.log)

However, We are unable to generate and retrieve the log files for the client(in Javascript). Please guide us on this point.

If the server logs are sufficient to decipher the reason for the disconnect event, please let us know anyway.

Regards,
Sandeep

**Comment by miguelgrinberg** [comment] 2019-12-24 23:25
These lines indicate that you have a problem with your application:

    b52c50d07c2b42b38de999e5de1ade4c: Client is gone, closing socket

Either your clients do not observe the Socket.IO protocol and fail to send the PING packet at the required interval, or (more likely) the server is blocked or too busy and cannot process these PING packets in a timely manner. What I've seen as the most common cause for this error is that the server does blocking operations, which are incompatible with an asynchronous eventlet server.

**Comment by sandeepckeerthi** [comment] 2020-01-01 11:03
Hi Miguel,

For second part of your answer, my server offloads the entire workflow to a thread as in the following snippet, so server is free to process PING/PONG packets

    wf = work_flow.get(current_user.get_id())
    if not wf:
        wf = work_flow.WorkFlow(current_user.get_id())
        work_flow.add(wf)
    keys = request.form['search_terms']
    interval = request.form['report_interval']
    print('Search Terms: ', keys)
    print('Report Interval: ', interval)
    keys = keys.strip().split()[0].strip()
    interval = int(interval.strip())
    wf.first_docid = None
    wf.thread_event = threading.Event()
    wf.thread = socketio.start_background_task(start_procs, wf.userid, keys, interval)
    return redirect(url_for('.search_results', keys=keys, interval=interval))

And I did not understand the part 'clients do not observe the Socket.IO protocol and fail to send the PING packet at the required interval'. I am using socket.io.js as Websocket client, why this library is failing to send PING packets?

Please let me know if I'm doing anything wrong here.

Regards,
Sandeep

**Comment by miguelgrinberg** [comment] 2020-01-06 08:18
As I said above, the problem is likely in the server, not the client.  If the server blocks, then it won't be able to process those PING packets that clients are sending. I assume you are using eventlet or gevent? If yes, have you monkey patched your standard library so that it becomes non-blocking?

**Comment by sandeepckeerthi** [comment] 2020-01-06 19:17
Yes. I'm using eventlet, and library is monkey patched. From last comment's code, `start_procs` does a Popen to a command and starts a thread(threading.Thread) for consuming messages from the rabbitmq using pika. Then it awaits the thread event looping `socketio.sleep()`.
How this is blocking the server. Do I have to use eventlet's tpool here?

**Comment by miguelgrinberg** [comment] 2020-01-06 19:22
Try the following test. Uninstall eventlet, then run the application again. It will work in threading mode, and will not have access to WebSocket. If your clients do not get disconnected, then it means that some call(s) that you are making are incompatible with eventlet and are blocking it.

**Comment by sandeepckeerthi** [comment] 2020-01-07 03:30
Uninstalled both eventlet and gevent. While it is running in threading mode, clients are still being disconnected, saying, 
> Client is gone, closing socket

Does this mean my code somewhere is still blocking the server?

**Comment by sandeepckeerthi** [comment] 2020-01-10 18:22
Hi Miguel,
May I request a kind response on this..

Regards
Sandeep

**Comment by miguelgrinberg** [comment] 2020-04-10 14:24
If you get the client is gone in threading mode I would make sure the client that you are using is compliant. In this mode it is less likely that you have a blocking issue.

**Closed** 2020-06-30 22:52 UTC
Labels: question
