### ISSUE TITLE
cannot connect to socket server always got 404 not found 

### ISSUE THREAD

**Issue by ziitel2** [miguelgrinberg/Flask-SocketIO#845] opened 2018-11-26 18:58 UTC
Hello !! Miguel 

**I have some question. I'm start using flask-socketIO for a few days
ago is actually work so well then in this day my server always gave me this Error :**

```
(30089) wsgi starting up on http://127.0.0.1:6000
(30089) accepted ('127.0.0.1', 35074)
127.0.0.1 - - [27/Nov/2018 01:19:01] "GET /socket.io/?EIO=3&transport=polling&t=1543256341451-0 HTTP/1.1" 404 366 0.001086
127.0.0.1 - - [27/Nov/2018 01:19:02] "GET /socket.io/?EIO=3&transport=polling&t=1543256342497-0 HTTP/1.1" 404 366 0.002342
127.0.0.1 - - [27/Nov/2018 01:19:03] "GET /socket.io/?EIO=3&transport=polling&t=1543256343507-0 HTTP/1.1" 404 366 0.002216
127.0.0.1 - - [27/Nov/2018 01:19:04] "GET /socket.io/?EIO=3&transport=polling&t=1543256344521-0 HTTP/1.1" 404 366 0.002261
127.0.0.1 - - [27/Nov/2018 01:19:05] "GET /socket.io/?EIO=3&transport=polling&t=1543256345533-0 HTTP/1.1" 404 366 0.001980
127.0.0.1 - - [27/Nov/2018 01:19:06] "GET /socket.io/?EIO=3&transport=polling&t=1543256346543-0 HTTP/1.1" 404 366 0.001821
127.0.0.1 - - [27/Nov/2018 01:19:07] "GET /socket.io/?EIO=3&transport=polling&t=1543256347554-0 HTTP/1.1" 404 366 0.002066
127.0.0.1 - - [27/Nov/2018 01:19:08] "GET /socket.io/?EIO=3&transport=polling&t=1543256348565-0 HTTP/1.1" 404 366 0.001630
127.0.0.1 - - [27/Nov/2018 01:19:09] "GET /socket.io/?EIO=3&transport=polling&t=1543256349575-0 HTTP/1.1" 404 366 0.001305

```
This is code for my server

```
from flask import Flask, render_template
from flask_socketio import SocketIO

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

if __name__ == '__main__':
    socketio.run(app, port="5001", **{"debug": True})
```
This is my code for testing 
```
from threading import Thread
from socketIO_client import SocketIO

host = 'localhost'
port = 5001

class TwoWayClient(object):
    def on_event(self, event):
        print(event)
    def on_status(self, event):
        print(event)
    def __init__(self):
        self.socketio = SocketIO(host, port)
        self.socketio.on('status', self.on_status)
        self.socketio.emit('connect')
        self.receive_events_thread = Thread(target=self._receive_events_thread)
        self.receive_events_thread.daemon = True
        self.receive_events_thread.start()
        while True:
            some_input = input()
            self.socketio.emit('text', some_input)

    def _receive_events_thread(self):
        self.socketio.wait()

def main():
    TwoWayClient()

if __name__ == "__main__":
    main()
```
Then i switch my client  code by using javascript( VueSocketio ) library as it been work well for a few days also same error still occur do you have any idea for my problem ?

**Comment by miguelgrinberg** [comment] 2018-11-26 22:48
Upgrade the flask-socketio and python-socketio packages to their latest version and let me know if that fixes the problem.

**Comment by ziitel2** [comment] 2018-11-27 07:46
Both of those package are the latest version.

**Comment by miguelgrinberg** [comment] 2018-11-27 08:59
You need to show me the output of the pup freeze command and the client and
server code that you are using.

**Comment by ziitel2** [comment] 2018-11-27 11:10
@miguelgrinberg
Sorry for late reply.  
It's my wrong. My friend find out the problem.

```
Flask==1.0.2
flask-cors==3.0.6
requests
beautifulsoup4
flask-socketio
gunicorn==19.9.0
eventlet==0.24.1
Flask-SQLAlchemy
psycopg2
Flask-MongoAlchemy==0.7.1
MongoAlchemy
kafka-python
python-socketio==2.0.0
Flask-WTF==0.11
WTForms==2.1
WTForms-JSON
```

After remove python-socketio every get back to work.
I'm still curious how this happen, Could you explain ?
Sorry for your times.

**Comment by ziitel2** [comment] 2018-11-27 11:12
Soory again, Should i close it by myself ?

**Comment by miguelgrinberg** [comment] 2018-11-27 11:13
You were probably using an old version, so the combination of releases that you were using were probably not compatible. In fact version 2.0.0 of python-socketio shown above is not the latest.

If the issue is fully resolved then yes, please close it. Thanks!

**Closed** 2018-11-27 12:33 UTC
Labels: question
