### ISSUE TITLE
Exception when accessing current_user (flask_login) from socketio handler if not logged in

### ISSUE THREAD

**Issue by jrestifo** [miguelgrinberg/Flask-SocketIO#638] opened 2018-02-10 03:13 UTC
```
from flask import request
from flask_login import current_user
from flask_socketio import send, emit
from . import socketio


@socketio.on('connect')
def connect_handler():
    if current_user.is_authenticated:
        pass
    else:
        return False
```

The above code causes this error when the user is not logged in:

```
connect handler error

Traceback (most recent call last):

File "/home/jrestifo/devel/bodangly/lotto/venv/lib/python3.5/site-packages/engineio/server.py", line 405, in _trigger_event

return self.handlers[event](*args)

File "/home/jrestifo/devel/bodangly/lotto/venv/lib/python3.5/site-packages/socketio/server.py", line 503, in _handle_eio_connect

return self._handle_connect(sid, '/')

File "/home/jrestifo/devel/bodangly/lotto/venv/lib/python3.5/site-packages/socketio/server.py", line 421, in _handle_connect

self.environ[sid]) is False:

File "/home/jrestifo/devel/bodangly/lotto/venv/lib/python3.5/site-packages/socketio/server.py", line 490, in _trigger_event

return self.handlers[namespace][event](*args)

File "/home/jrestifo/devel/bodangly/lotto/venv/lib/python3.5/site-packages/flasksocketio/init_.py", line 243, in _handler

*args)

File "/home/jrestifo/devel/bodangly/lotto/venv/lib/python3.5/site-packages/flasksocketio/init_.py", line 624, in _handle_event

ret = handler()

File "/home/jrestifo/devel/bodangly/lotto/app/socketio.py", line 12, in connect_handler

if current_user.is_authenticated:

File "/home/jrestifo/devel/bodangly/lotto/venv/lib/python3.5/site-packages/werkzeug/local.py", line 343, in getattr

return getattr(self._get_current_object(), name)

File "/home/jrestifo/devel/bodangly/lotto/venv/lib/python3.5/site-packages/werkzeug/local.py", line 302, in _get_current_object

return self.__local()

File "/home/jrestifo/devel/bodangly/lotto/venv/lib/python3.5/site-packages/flask_login.py", line 47, in <lambda> current_user = LocalProxy(lambda: _get_user())

File "/home/jrestifo/devel/bodangly/lotto/venv/lib/python3.5/site-packages/flask_login.py", line 858, in _get_user current_app.login_manager._load_user()

File "/home/jrestifo/devel/bodangly/lotto/venv/lib/python3.5/site-packages/flask_login.py", line 366, in _load_user deleted = self._session_protection()

File "/home/jrestifo/devel/bodangly/lotto/venv/lib/python3.5/site-packages/flask_login.py", line 402, in _session_protection

if mode == 'basic' or sess.permanent:

AttributeError: 'dict' object has no attribute 'permanent'
```

For now I just wrap it in a try, except block and return False (disconnect the user) on an exception. Doesn't make me feel nice doing so.

**Comment by jrestifo** [comment] 2018-02-10 05:07
I am using "strong" session protection

**Comment by jrestifo** [comment] 2018-02-21 08:32
Hi Miguel just wondering if you have any more info on this bug. Is my workaround to wrap the code which accesses current_user in a try except block safe from a security standpoint?

**Comment by miguelgrinberg** [comment] 2018-02-21 17:15
@jrestifo in terms of security what you are doing is fine, but I intend to fix this. The problem is that Flask-SocketIO creates its own sessions, and uses dictionaries for them, which works almost always, except when code tries to access the attributes of the Flask session object, such as `session.permanent`. I need to use a session object that is or looks more like the real thing.

**Comment by bsherin** [comment] 2018-02-25 16:44
I just wanted to reply to give this a plus one. My server is throwing this same error regularly. Is the workaround above the right one?

**Comment by miguelgrinberg** [comment] 2018-02-25 17:38
@jrestifo @bsherin I'm actually unable to reproduce this problem using the latest Flask-Login version 0.4.1. What version are you using?

**Comment by miguelgrinberg** [comment] 2018-02-25 17:51
This bug is now fixed in release 2.9.4.

**Closed by miguelgrinberg** 2018-02-25 17:51 UTC
Labels: bug

**Comment by bsherin** [comment] 2018-02-25 20:05
Oh, thanks much. I was running 2.9.3 and I didn't realize there is a new version

**Comment by jrestifo** [comment] 2018-02-28 01:28
Thank you!
