### ISSUE TITLE
No handling of further requests while busy with binary data

### ISSUE THREAD

**Issue by Schnodderbalken** [miguelgrinberg/Flask-SocketIO#378] opened 2016-12-12 16:03 UTC
When I make a socket.io client request to the flask application with a binary content of a bigger size (in my tests a file with 12MB) the server is unable to resolve any requests during the time of processing.

Here is what the whole thing looks like from the client side:
http://fs5.directupload.net/images/161212/mrxq6hik.png

As it can be seen there is the request with binary content then many additional requests and then a waiting time of 12 seconds until the server responds to the new requests (this is the time the server needs to process the first request).
If I print something in the @socketio.on function it does not get printed until the first request is processed (including the print for the first request itself). It kind of seems like there is no parallel processing of requests at all and I only notice it now more than ever because there is one big request that lasts for a few seconds.
It also does not work if I try to connect with another client to the server during that time.

The worst case scenario would be a client uploading like 1GB to the server making any other request unable to get through.

I am using eventlet as async_mode and monkeypatched it. These are the versions of the pieces of software I use:

socket.io client: 1.7.1
Flask: 0.11.1
flask-socketio: 2.8.1
eventlet: 0.20.0

Any ideas?

**Comment by miguelgrinberg** [comment] 2016-12-12 17:54
Do you have example code I can use to reproduce this problem?

**Comment by Schnodderbalken** [comment] 2016-12-12 21:21
I created a setup with a client (html+js) and a server. You can download it from here:
http://s000.tinyupload.com/?file_id=71123224369190720394
The necessary reproduction steps are rendered in the html.

**Comment by miguelgrinberg** [comment] 2016-12-12 22:55
I see the delay with a 100MB file. With a 10MB file there is no perceptible delay. With a 1GB file, Chrome crashes a few seconds after the upload begins.

The test button does not respond while the upload takes place, but if I connect with another browser I get immediate responses, unlike your report that suggests all clients are blocked. I noticed that both Chrome and Safari show the beachball for a few seconds after I select the file to upload. So part of the delay is I think, actual transmission of the payload.

The reason you cannot send the test messages until after the upload completes is that the packets in the WebSocket connection share a single connection. Once the big packet starts sending, nothing else can be sent until that completes. You can open a separate connection for uploads if you want to always have low latency access for the short messages. Or actually, you may want to consider doing your uploads with HTTP. At those payload sizes you are not going to see any significant performance difference using WebSocket.

Based on some initial debugging, it appears this large binary packet takes very long to be received and/or processed by eventlet's websocket implementation. The Socket.IO logging on the server indicates that as soon as the packet is received it is delivered to your handler.

So I can't really give you a solution right away. This will require debugging the eventlet implementation to see where the delay is happening.

**Comment by Schnodderbalken** [comment] 2016-12-12 23:30
> The test button does not respond while the upload takes place, but if I connect with another browser I get immediate responses, unlike your report that suggests all clients are blocked. I noticed that both Chrome and Safari show the beachball for a few seconds after I select the file to upload. So part of the delay is I think, actual transmission of the payload.

The fact that immediately after initiating the upload there is no reaction on the client side is probably due to the upload blocking everything because javascript in the browser can not handle multiple threads (without using workers).

I find it strange that it behaves differently on our systems. For me, even opening a new connection (e.g. by opening a new browser window) while the (10MB!) file is being uploaded does not result in an immediate response. What you described above is the behavior I would have expected and accepted.

In my case it would not help to use a separate connection for uploads because additional connections do not seem to be handled while there is an upload going on.
Well, using HTTP for that would be a possible solution. However, I hesitate to have an additional HTTP server running only for the purpose of handling uploads that are supposed to work with socket.io as well.

All in all since we both used the exact same code for the client and the server side I assume that the cause must be a system difference (which affects the server side) but I can't imagine what that might be.

**Comment by Schnodderbalken** [comment] 2016-12-12 23:42
By the way this also happens if I provide debug=True in the run method of socket.io. In this case it defaults to werkzeug. So it does not seem to be an issue of eventlet..hmm..confusing.

**Comment by miguelgrinberg** [comment] 2016-12-12 23:43
> However, I hesitate to have an additional HTTP server running only for the purpose of handling uploads

You are already running an HTTP server. All the Socket.IO communications until the WebSocket connection is established run on HTTP. All you need to do is add a Flask route for your uploads, something like:

```python
@app.route('/upload', methods=['POST'])
def upload_file():
    # handle uploads here
    pass
```

> By the way this also happens if I provide debug=True

Eventlet is used even if you run in debug mode. If you uninstall eventlet from your virtualenv you will force the Werkzeug server to be used.

**Comment by Schnodderbalken** [comment] 2016-12-12 23:45
Okay, I will give it a try with that. Thank you!

**Comment by yeomanxu** [comment] 2018-07-03 00:36
Hello,do you solve this problem?I have the same problem too,it has confused me three days.How to solve it?thank you

**Comment by moshisushi** [comment] 2018-07-09 21:01
@miguelgrinberg I have Implemented my socketIO + upload server the way you describe, but it actually seems like the upload blocks the event loop (even if I do the HTTP based upload in one browser tab/window and and use the chat in other windows). I've removed all the handling logic from the upload handler to make sure nothing else could be blocking, but makes no difference.

If you like, you can have a look at the code I'm testing with here:
https://github.com/r3u/portals-reconlive-av/blob/master/app/server.py

(the asset_manager function is the upload endpoint, which is the one I replaced with an empty 'pass' body to rule out other things blocking).

Any ideas?

**Comment by miguelgrinberg** [comment] 2018-07-09 21:16
@moshisushi is this a really big file? The problem could be that file I/O is not asynchronous. If you need to save a big file to disk you may need to move that to another thread. See http://eventlet.net/doc/threading.html.

**Comment by moshisushi** [comment] 2018-07-09 21:34
@miguelgrinberg Yeah the issue is with big files (testing with 100 MB). The thing is that it blocks even if I remove the save to disk step, but perhaps Flask is saving to disk internally anyway (i.e file.save function call is perhaps really just a rename from a temporary file to a permanent location)? I'm familiar with the tpool stuff but I don't understand how I would make my whole @app.route-ed endpoint run in a thread.

**Comment by miguelgrinberg** [comment] 2018-07-09 22:04
@moshisushi oh right, I did not consider that Flask/Werkzeug save the upload to a temp file. This is a tricky one, support for asynchronous file I/O has not been standardized, so there is no support for that. Maybe you can change your application to upload the file in small chunks via Socket.IO? I don't think there are any easy solutions for this.

**Comment by moshisushi** [comment] 2018-07-09 22:09
@miguelgrinberg Thanks for clarifying! I might be better off splitting it into two services then, with HTTP uploads simply happening in different python processes. I can use redis backed flask-socketio to emit from the upload service to the chat service perhaps?

**Comment by miguelgrinberg** [comment] 2019-06-08 14:53
I don't think this is an issue with this package, the blocking behavior is due to file I/O not being asynchronous. Closing.

**Closed by miguelgrinberg** 2019-06-08 14:53 UTC
Labels: investigate
