### ISSUE TITLE
Node.js client can't connect

### ISSUE THREAD

**Issue by kurisubrooks** [miguelgrinberg/Flask-SocketIO#247] opened 2016-03-22 01:30 UTC
I've followed the documentation, but i'm unable to get the client to connect to the server at all. 
I've tried manually setting the IP, Port, in both client and server, but i'm unavailable to get it to connect and pass events. Any help?

server.py:
```python
#!/usr/bin/env python

import sys, os
if (sys.version_info[0] < 3):
    print("Server requires Python 3+ `\n")
    raise

from tweepy import Stream, OAuthHandler
from tweepy.streaming import StreamListener
from flask import Flask, render_template
from flask_socketio import SocketIO, emit
from colorama import Fore
import json

app = Flask(__name__)
app.config["SECRET_KEY"] = ""
socket = SocketIO(app)

API_KEY = ""
API_SECRET = ""
ACCESS_TOKEN = ""
ACCESS_TOKEN_SECRET = ""

kurisubrooks = "1875425748"

user = kurisubrooks
version = "2.0"

with open("file.json") as data_file:    
    stuff = json.load(data_file)

@app.route('/')
def index():
    return render_template('index.html')

@socket.on('ping')
def game(message):
    emit('pong', {'response': 'received', 'message': message})

class listener(StreamListener):
    print(Fore.GREEN + "[!] Twitter Listener Started: " + user)

    def on_data(self, data):
        tweet = json.loads(data)

        if tweet["user"]["id_str"] == user:
            print(Fore.BLUE + "[*] Tweet Receieved")
            parse(tweet["text"])

    def on_error(self, status):
        print(Fore.RED + "[!] API Error " + str(status))

def parse(input):
    try:
        data = input.split(",")
        output = { 'data': data }

        print(Fore.YELLOW + str(output))
        socket.emit("data", output)
    except Exception as e:
        print(Fore.RED + str(e))
        socket.emit("error", { "error": e })

if __name__ == "__main__":
    auth = OAuthHandler(API_KEY, API_SECRET)
    auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)

    stream = Stream(auth, listener())
    stream.filter(follow=[user])

    socket.run(app, host='0.0.0.0', port=1190, debug=True)
```
client.js:
```javascript
const socket = require('socket.io-client')('http://0.0.0.0:1190');

socket.on('connect', () => {
    console.log('Connected to Socket');
    socket.emit('ping', {});
});

socket.on('pong', () => console.log('Received Pong from Server'));
socket.on('disconnect', () => console.log('Disconncted from Server'));

console.log('Started');
```

I've had to censor and remove some parts for our safety, but the general socket code still exists above.

**Comment by miguelgrinberg** [comment] 2016-03-22 05:38
This is in my list of bugs to fix for the next release. See #219.

**Comment by kurisubrooks** [comment] 2016-03-22 05:45
Just tested the fix in that issue but i'm still not receiving any connect/handshake.
Because I need this for a critical production ready program ASAP, would you be able to recommend any other working socket.io servers written in python? I'd be very grateful!

**Comment by miguelgrinberg** [comment] 2016-03-24 17:59
I don't know of any other socket.io server that works with the 1.x socketio clients. Sorry.

I'm closing this issue, since it is a duplicate of #219.

**Closed by miguelgrinberg** 2016-03-24 17:59 UTC
