### ISSUE TITLE
Run with Celery

### ISSUE THREAD

**Issue by item4** [miguelgrinberg/Flask-SocketIO#169] opened 2015-11-02 08:39 UTC
I'm interested in socket.io implemenation with python, and I want to use it with celery.

So far as I know, Flask-Socketio isn't compatible with Celery, if so. Is there any other way to use two framework both?

If I want to use it with celery, what info is must be keep for sending to each user/connection?

**Comment by miguelgrinberg** [comment] 2015-11-02 15:47
I would not say that this extension is incompatible with Celery as a blanket statement. The issue is that only the Flask process can communicate with clients. You can easily make any process communicate with clients if those processes pass the messages they want to send out to the Flask process.

I'm working on a Redis backend for a future release that will simplify this task, but implementing a specific use case should not be hard at all. Just use the pub/sub feature of Redis to allow any external process (i.e. the Celery worker) to relay messages to be sent out to clients to the Flask process.

**Comment by gordol** [comment] 2015-11-03 07:55
@item4 see my example here: https://github.com/miguelgrinberg/Flask-SocketIO/issues/47#issuecomment-153281313

**Comment by miguelgrinberg** [comment] 2015-12-14 01:29
I'm closing this as a duplicate of #47. This feature is soon going to be available, see the update I just posted on #47.

**Closed by miguelgrinberg** 2015-12-14 01:29 UTC
Labels: enhancement, question
