### ISSUE TITLE
[ImportError] ModuleNotFoundError: No module named 'socketio.exceptions'

### ISSUE THREAD

**Issue by crhodes2** [miguelgrinberg/Flask-SocketIO#1678] opened 2021-09-08 16:34 UTC
All I am trying to do is have the flask-socketio module installed and running onto my flask server application.
I have done the pip install, and tried to plug in the import and I keep getting this error.` **from flask_socketio import SocketIO** `
and as a result, I keep getting this error.
```
Traceback (most recent call last):
  File "app.py", line 10, in <module>
    from flask_socketio import SocketIO
  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 22, in <module>
    from socketio.exceptions import ConnectionRefusedError  # noqa: F401
ModuleNotFoundError: No module named 'socketio.exceptions'

```
Is this how the module supposed to work? How can I move away past this? I have recreated possible solutions online using the following links, but the issue refuses to go away.
https://github.com/miguelgrinberg/Flask-SocketIO/issues/1105

Whoever build this module, I'm sorry to say but I absolutely abhor your module. It has done nothing but drive me crazy all week trying to run this to my Flask server, I am debating about moving away from it.

**Comment by miguelgrinberg** [comment] 2021-09-08 19:27
> I'm sorry to say but I absolutely abhor your module

This is not a good way to ask for help. The person who built this module is the person that will try to help you, so yeah, I get that you are frustrated, but without offending you, you have to consider that thousands of users use this package, so this is likely your own user error.

Also, if I may complain myself as well, you have written an "issue" on this repository, while in fact you don't know if there is an issue or if the issue is yours. Issues are for bugs that I need to work on. If you have a question, need help, or don't know where the issue is, the proper thing to do is to open a discussion. I'm moving this to a discussion now.

No, on to your issue: My guess is that you have installed a set of dependencies that are incompatible with each other. So start by upgrading flask-socketio to the latest version with this command:

    pip install --upgrade flask-socketio

This should bring everything to the latest versions. If you continue to have errors after this, let me know.

**Closed** 2021-09-08 19:27 UTC
