### ISSUE TITLE
Need to erase cache everytime front end code is updated

### ISSUE THREAD

**Issue by luisArandas** [miguelgrinberg/Flask-SocketIO#1311] opened 2020-06-21 13:06 UTC
Hello!

I think this is a silly question but I can't figure out a quick way around it.  

I am using this library and when I am working on the front-end, every time I update a .js file (not happening with index.html) of my app I need to clear cache of the browser to test the newly introduced code (currently working with Chrome vs 83.0.4). When working with node and yarn this seems to not be the case. Is there any quick way around it? The objective would be every refresh to get the new saved files. 

I saw the flask-cache library but before I turn that way I want to be sure I am doing everything the right way. 

Thanks in advance.

**Comment by miguelgrinberg** [comment] 2020-06-21 13:41
Closing as duplicate of #1310

**Closed by miguelgrinberg** 2020-06-21 13:41 UTC

**Comment by snbck** [comment] 2020-06-23 08:15
😓

**Comment by luisArandas** [comment] 2020-06-23 09:28
Please erase this issue, I just posted same text of #1310
