### ISSUE TITLE
Websockets not handling response

### ISSUE THREAD

**Issue by EndenDragon** [miguelgrinberg/Flask-SocketIO#821] opened 2018-10-26 20:49 UTC
When i start the gunicorn (eventlet) process, first few connections works fine. However, after a minute or so, the issues arises.
From my nginx error log, i first see lots of:
`2018/10/26 20:41:33 [error] 31364#31364: *610983 recv() failed (104: Connection reset by peer) while proxying upgraded connection, client: 87.88.8.24, server: titanembeds.com, request: "GET /gateway/?EIO=3&transport=websocket HTTP/1.1", upstream: "http://unix:/var/www/titanembeds_ws.sock:/gateway/?EIO=3&transport=websocket", host: "titanembeds.com"`
Then after a while it becomes more of 
`2018/10/26 20:42:43 [error] 31364#31364: *635544 connect() to unix:/var/www/titanembeds_ws.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: 75.27.24.47, server: titanembeds.com, request: "GET /gateway/?EIO=3&transport=websocket HTTP/1.1", upstream: "http://unix:/var/www/titanembeds_ws1.sock:/gateway/?EIO=3&transport=websocket", host: "titanembeds.com"`

I am using multiple services to handle /gateway/ endpoint
Nginx sites enabled config includes:
```
upstream uwsgititanws {
    ip_hash;
    server unix:/var/www/titanembeds_ws.sock max_fails=0;
    server unix:/var/www/titanembeds_ws1.sock max_fails=0;
    server unix:/var/www/titanembeds_ws2.sock max_fails=0;
}
```
The command to run the gunicorn process is as follows:
`/usr/bin/python3 /usr/local/bin/gunicorn --worker-connections 4096 --worker-class eventlet -w 1 -b unix:/var/www/titanembeds_ws.sock titanembeds.app:app`

Now I like to add that this issue only appears during peak times. (Hundreds of connections, for a few hours a day)

When the services/processes are restarted, I can see upwards of hundreds of connections on my counter. But when the errors show up on the logs, the connection count jumps down to tens from hundreds.

I have monkey patched the code in the [first line](https://github.com/TitanEmbeds/Titan/blob/master/webapp/titanembeds/app.py) of `titanembeds.app:app`.

(By the way @miguelgrinberg, do you offer service to personally take a look at the server and resolve the issue?)

**Comment by EndenDragon** [comment] 2018-10-26 22:30
This is the specs of my server using screenfetch.
```
root@titan:/home/endendragon# screenfetch
                          ./+o+-       root@titan
                  yyyyy- -yyyyyy+      OS: Ubuntu 18.04 bionic
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 4.15.0-36-generic
           .++ .:/++++++/-.+sss/`      Uptime: 5h 20m
         .:++o:  /++++++++/:--:/-      Packages: 882
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 4.4.19
       .:+o:+o/.          `+sssoo+/    CPU: Intel Xeon E5-1650 v3 @ 4x 3.5GHz
  .++/+:+oo+o:`             /sssooo.   GPU: EFI
 /+++//+:`oo+o               /::--:.   RAM: 3169MiB / 3944MiB
 \+/+o+++`o++o               ++////.  
  .++.o+++oo+:`             /dddhhh.  
       .+.o+oo:.          `oddhhhh+   
        \+.++o+o``-````.:ohdhhhhh+    
         `:o+++ `ohhhhhhhhyo++os:     
           .o:`.syhhhhhhh/.oo++o`     
               /osyyyyyyo++ooo+++/    
                   ````` +oo+++o\:    
                          `oo++.      
root@titan:/home/endendragon# 
```

**Comment by miguelgrinberg** [comment] 2018-10-26 22:55
The specs by themselves don't tell me much. As I said above, you need to make sure you are not overworking your server processes. Watch your CPU, RAM, filehandle count, logs, etc. during an occurrence of this problem to try to find where the problem is.

**Comment by EndenDragon** [comment] 2018-10-28 00:48
So I packed up my websocket workers and moved it to a separate dedicated server. I also switched to gevent-websockets.
When I enable engineio logging, I see alot of `Received packet MESSAGE data 2/gateway` (receiving from client) and next to none of `Sending packet MESSAGE data 0/gateway` (sending to client). Would that be related to overworking the server processes? Nginx is no longer complaining about dropped connections (browser indicate 101 status code), but flasksocketio is not responding to the client. Most of the emits received from the client flask socketio should respond to. 
When I look in `htop` to see the the load, about 75% of the 4-core cpu is used and half of the ram is used.

**Comment by miguelgrinberg** [comment] 2018-11-03 08:44
@EndenDragon Are you sure your application works as you expect? If messages aren't sent, that probably means a logic problem, not load related. If it was load, messages would take a long time to arrive, but they would appear in the logs and eventually reach the client.

**Comment by EndenDragon** [comment] 2018-11-03 18:37
@miguelgrinberg I presume it is a load problem because flask socketio sends `3` a long time after the browser sent `2`.

**Comment by miguelgrinberg** [comment] 2018-11-03 18:45
It could be blocking too. If any of your handlers are blocking that will prevent Flask-SocketIO's service thread from replying timely to those pings. Are you doing anything that could be blocking? Even if you monkey patch, some things are not compatible with eventlet's asynchronous model and could block the process.

For example, running a loop that performs a long calculation would block every other task in the system from running. It may look like load, but this problem is easily addressed by adding `sleep(0)` calls inside the loop, so that other tasks get their share of the CPU while the loop is running.

**Comment by EndenDragon** [comment] 2018-11-03 18:55
Could it be `flask_redis` package? I am making redis calls.

**Comment by miguelgrinberg** [comment] 2018-11-03 18:56
That should be fine if you monkey patched. That makes all socket operations compatible with eventlet.

**Comment by EndenDragon** [comment] 2018-11-03 18:58
For `time.sleep(0)`, does it matter the placement? Should it be at the beginning, middle, or end of the for loop?

**Comment by miguelgrinberg** [comment] 2018-11-03 19:00
Placement does not matter. It should be done often enough though. If you spend a long time doing CPU work, then nothing else happens during that time. The multitasking done by eventlet is cooperative, each task needs to release the CPU often, either indirectly by doing I/O or directly by sleeping.

**Comment by EndenDragon** [comment] 2018-11-03 19:34
I've added time.sleep() to many of the for loops. I don't notice any performance increase with the additions.

**Comment by EndenDragon** [comment] 2018-11-03 20:00
One thing that I noticed is getting disconnected after a minute or less. The browser would send a `2` and the server disconnects the browser after sending a `41/gateway`.

**Closed** 2019-04-07 10:09 UTC
Labels: question
