### ISSUE TITLE
Ordering of incoming messages

### ISSUE THREAD

**Issue by mortoray** [miguelgrinberg/Flask-SocketIO#1420] opened 2020-11-30 20:45 UTC
On a single-process server, does @socketio.on process incoming messages in order, in sequence, or can it process messages in parallel? In particular from a single client.

I'm attempting to debug an issue I have where a sequence of three messages came, say with ids 4,5,6. My handler looks roughly like this:

```
@socketio.on('game', namespace='/game')
def handle_game_event(event):
   event_id = redis.incr('counter')
   event_out = {**event, 'id': event_id}
   redis.rpush(event_out)
   emit('game', event_out, broadcast=True, room=event['room'], namespace='/game')
```

The issue I'm having is that it appears the `redis.incr` was called in order on 4,5,6. But then `rpush` was called out of of order `6,4,5`. This would be expected if there are asynchronous incoming event handlers for a single room. I'm relying on the rooms messages being processed in-order and fully. If not there's no way I can maintain proper ordering -- since even if call just `redis.rpush` first, another message could still come in at the same time and get pushed out-of-order.

**Comment by miguelgrinberg** [comment] 2020-11-30 22:52
The event handlers will be dispatched in the order they arrive, but in the default configuration of the server you can end up with more than one event running at the same time, since the server does not wait for an event handler to return before dispatching the next event.

If you prefer that there is only one handler per client running at a given time, then set `async_handlers=False` in the `SocketIO()` constructor.

**Comment by mortoray** [comment] 2020-12-01 05:49
I'll try making it synchronous for now.

Does this affect the SocketIO only, or also the flask incoming HTTP connections?

Would it be feasible to make it synchronous per room  only, and not globally?  Or is there any other option for ensuring a sequenced processing of events? Surely somebody else must have run into this situation and have a similar need.

**Comment by miguelgrinberg** [comment] 2020-12-01 08:29
The `async_handlers` setting is for Socket.IO events only. You can prevent messages from running in parallel yourself by adding critical sections around the messages that are never supposed to run at the same time. For example:

```python
from threading import Lock

lock = Lock()

@sio.on('event1')
def event1(data):
    with lock:
        # do stuff here

@sio.on('event2')
def event2(data):
    with lock:
        # do stuff here
```

**Comment by mortoray** [comment] 2020-12-01 10:08
I don't believe the `lock` approach will work, since there's still no guarantee the locks are acquired in order if there are two incoming requests.  We'd need something like a @sio.lock(lock) that communicates it properly to the dispatcher.

**Comment by miguelgrinberg** [comment] 2020-12-01 10:11
The functions will be invoked in order, so there is no way the second event can take away the lock from the first. This of course assumes you are using greenlets. If you are using real threads then you would be correct, there is no way to predict who'll get the lock first.

**Comment by mortoray** [comment] 2020-12-01 12:08
Right, since it'll only switch when it hits another async-call/coroutine. Though, given that 99% of my messages need to go through one locked function, I might as well make all the handlers sync. It'll likely be the same performance. Hopefully the overall performance is still good.

**Comment by mortoray** [comment] 2020-12-01 13:39
I've tested with `async_handlers=False` and my throughput speed increases. I'll go with this approach.

**Comment by mortoray** [comment] 2020-12-01 14:15
It appears to still be processing messages out of order on the client side. Is there a similar `async_handlers` argument for the `socketio.Client()`?

It appears that different events are still processed in parallel. I tested this on the server by checking for re-entrancy in a shared function that emits messages.  While a `game` event is processing it's possible for a `join` event to interrupt it.  You seemed to indicate this shouldn't happen though.

**Comment by mortoray** [comment] 2020-12-01 14:36
I setup like this:

```
socketio = SocketIO(app, cors_allowed_origins="*", async_handlers=False)
```

And my event function looks like this now. The code prints "!!!BAD" sometimes indicating it is called a second time before the first one exits. The print `print` event then shows msg_id's that are out of order.

```
pge_inside = False
def publish_game_event( client_id, key, event, broadcast=True ):
	global pge_inside
	if pge_inside:
		print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!BAD")
	pge_inside = True
		
	msg_id = rnx.next_message_id(key) # Produces incrementing counter from Redis
	event_out = {
		**event,
		'msg_id': msg_id,
		'client_id': client_id,
		'when': datetime.datetime.utcnow().isoformat(),
	}
	# not part of published message
	event_out.pop('key',None)
	
	rnx.push_message(key, event_out)
	if broadcast:
		emit('game', event_out, broadcast=True, room=key, namespace='/game')
	else:
		emit('game', event_out, broadcast=False, namespace='/game')
		
	print(event_out)
	pge_inside = False
```

**Comment by mortoray** [comment] 2020-12-01 14:59
I've traced this back into _handle_event(self, sid, namespace, id, data):` in the server class. The re-entrancy is already happening there with multiple clients attached.

**Comment by miguelgrinberg** [comment] 2020-12-01 15:01
The client implementation does not currently have the async_handlers option, it always invokes handlers as the events arrive, regardless of having handlers still running. The server offers this option just for compatibility with older versions, but when I built the client I decided it is not a useful option, since the application can easily implement their own serialization or critical sections as needed in each particular case.

The server-side async_handlers=False option prevents two or more messages from a given client from running concurrently. Events from different clients can still occur in parallel.

**Comment by mortoray** [comment] 2020-12-01 15:04
Given the high-level of contention the Lock approach is not useful. The performance plummets considerably.

So I have no way to properly sequence incoming events. :(

**Comment by miguelgrinberg** [comment] 2020-12-01 15:17
Did you try with a queue?

**Comment by mortoray** [comment] 2020-12-01 16:06
I've tried with a Redis queue in the original connection. I'm now trying with one during the callbacks. It appears the contention is super high though, making it super slow. I'm trying to figure out where the problem is.  I'd prefer if there was a way to tell engineio not to multiplex in the first place, keep it single threaded from the start.

**Comment by miguelgrinberg** [comment] 2020-12-01 18:18
You can use a `Queue` object, that should be lighter than Redis. But in any case, I'm not sure how this contention that you refer to is going to be different if it is the library doing the serialization. If you receive a large number of events more or less at the same time and you don't want them to be handled in parallel I don't see how you can avoid contention. You can move it form one side to the other, but how can you make it disappear?

**Comment by mortoray** [comment] 2020-12-01 19:53
I'm trying various queues now.

The contention is artificial here. I assume somewhere at the lower levels there is a single listener that is handling all of the incoming connections.  That's how the OS works. Then something is splitting out the messages per client. Ideally I'd find where that is happening and tell it to not do that, to handle everything synchronously.

**Comment by mortoray** [comment] 2020-12-01 19:57
How can I emit back to a specific client without being in the request for that client?

**Comment by mortoray** [comment] 2020-12-01 21:10
It appears I can't emit to the socketio layer from a separate queue handling thread:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/src/escape-live/server/server.py", line 478, in pge_worker
    emit('game', event_out, broadcast=True, room=key, namespace='/game')
  File "/src/escape-live/env/lib/python3.8/site-packages/flask_socketio/__init__.py", line 786, in emit
    socketio = flask.current_app.extensions['socketio']
  File "/src/escape-live/env/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/src/escape-live/env/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/src/escape-live/env/lib/python3.8/site-packages/flask/globals.py", line 52, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.
```

Is there not some way of telling the engineio layer not to multiplex the messages?  Otherwise I have to find an entirely different solution, probably rebuild all of Flask-SocketIO.

**Comment by mortoray** [comment] 2020-12-01 21:18
Okay, I got the queue approach working as well, but it slows to a crawl (like from 1200msgs/s down to 70/s). There's no likely way to avoid this contention without getting EngineIO to not split off the incoming messages.

**Comment by miguelgrinberg** [comment] 2020-12-01 23:11
I don't understand. Are the 1200 msgs/s without parallelism? How long does each event runs for on average?

**Comment by mortoray** [comment] 2020-12-02 05:43
The 1200msgs/s is without trying to keep the messages in order, it's with async_threads=False, but directly emitting to each room. The server is essentially an echo processor, so I don't have overhead at the high-level.

I've recreated the situation without Redis involved, showing it's not the problem.  Here is the code I currently have that processes the messages (publish_game_event is called from a @socketio.on(...) handler -- an extra one at connect time, but then only one).

```
pge_enter = 0
pge_queue = queue.SimpleQueue()

def publish_game_event( client_id, key, event, broadcast=True ):
	global pge_enter
	dup = {
		**event,
		'client_id': client_id,
		'when': datetime.datetime.utcnow().isoformat(),
	}
	pge_queue.put((key, dup))


msg_id = 0
def pge_worker():
	global msg_id
	while True:
		key, qevent = pge_queue.get()
		msg_id += 1
		event_out = {
			**qevent,
			'msg_id': msg_id,
		}
		socketio.emit('game', event_out, broadcast=True, room=key, namespace='/game')
```

With a single client attached this gets (now without Redis) 1700msgs/s throughput (measured from the test client). Adding a second client and it drops to 90msgs/s.  This is with both clients joining the same room (the same "key" in the above). If they join different rooms the timing is erratic, from 200-2200 (I'm not sure how it goes faster sometimes).

Note that if I don't use the Queue, if put the pge_worker loop inline with the publish_game_event, then the system sustains the high throughput (1700msgs/s), even with both clients connected to the same room.  

I tried another solution not using a worker, but passing through Redis and flushing inside publish_game_event. This exhibited the same problem as the Queue. So I don't think the Queue itself is introducing the bottleneck.

**Comment by miguelgrinberg** [comment] 2020-12-02 10:15
Okay, so `async_handlers=False` guarantees that messages that arrive from a given client arrive in the correct order and are serialized (i.e. a message is not dispatched until the previous one returns). Do we agree that this is correct?

But the problem is that you need messages across all the clients that are in a room to be serialized, not just for each client separately. If I understand this correctly, then how do you expect this can be done more efficiently from the library side?

**Comment by mortoray** [comment] 2020-12-02 12:08
Yes, I agree with the first one.

And yes, I need all messages in a room to have a defined total order, my handlers called in that order, and resulting messages dispatching in the order I send them.  I'd expect the library, as soon as it receives a message for a room, to put it in a FIFO queue right then and dispatch them from the queue.  I'd suspect the library has a much better control as to the synchronization than I do at a high-level.

Though perhaps it's enough if we figure out why my queue approach is so slow. In theory we're still sending the same messages to all the same clients. This would mean we have to cross connection bounds already, and already be synchronized.  Would it help if I wrote a standalone example that could demonstrate the slow-down?

**Comment by miguelgrinberg** [comment] 2020-12-02 14:42
There is no concept of "all the messages in a room". Note my choice of words, I said "messages across all the clients that are in a room". Messages come from individual clients, the fact that a client is in a room does not change anything, and in fact the client can be in many different rooms at the same time. So basically you want messages from two or more clients to be serialized against each other, based on the clients being together in one specific room you care about.

It is expected that you will have a big performance drop when you prevent parallelism via locks or queues. It seems you want to do the serialization without giving up the performance, and that is not realistic. I'm sure there is a bit of overhead introduced by the lock or queue, but at the end of the day, the problem is that only one event is running at a given time, versus several in the unrestricted case.

**Comment by mortoray** [comment] 2020-12-02 15:06
Client messages are sent to a specific room, are they not? That means there is a concept of all the messages in the room.

I expect a drop, but not this much of a drop. There must be some kind of artificial bottleneck somewhere. My point is that the same level of synchronization has to happen already, since all the messages need to be dispatched to all the clients in the same room.  And the Queue I'm adding on top is not what is is adding the overhead -- otherwise other rooms would be impacted as well.

Additionally, pushing messages to Redis, and incrementing a counter, don't significantly slow down the performance, and that's serialized across processes. That's why I'm saying there's something fishy going on that is highly unexpected. The performance drop I'm seeing is way beyond what is expected.

**Comment by miguelgrinberg** [comment] 2020-12-02 15:24
You seem to have some misconceptions:

- Clients can only send messages to the server. They cannot send messages to other clients, and the have zero visibility into rooms. The server is always the recipient of emits from the client.
- The server can emit to clients one at a time. If the server emits to a room, internally there is a for-loop that emits to each client that was added to the room individually. There is no magic broadcast that you can use to send data once and have it sent to multiple clients.

> I expect a drop, but not this much of a drop.

As I said, you are preventing concurrency so of course things are going to slow down. Unless you measure everything and come up with evidence to the contrary, I have to assume that the serialization is causing the slow down.

> There must be some kind of artificial bottleneck somewhere.

Yes. You don't have concurrency anymore.

> My point is that the same level of synchronization has to happen already, since all the messages need to be dispatched to all the clients in the same room.

No. There is no concept of a room when receiving messages, as I explained several times already. There is also no synchronization needed between clients, the server maintains a separate network socket for each client and these sockets are asynchronous and fire independently when data arrives.

**Comment by mortoray** [comment] 2020-12-02 15:37
I understand how the rooms work, and this is why I'm surprised that I have a bottleneck. Let me try to explain a bit better my evidence showing something weird.

In the async, default case, this is what I understand happens, with several clients who have joined the same room:

(Several possible in parallel)
- A client sends a message
- The message arrives at my handler
- My handler calls emit, with Broadcast=True on that message
- SocketIO, does a loop over the clients, emitting it to each client in the room
- The handler returns

Now, in my case, with an intervening Queue, this is what happens:
(Each client processes one at a time, not in parallel)
- A client sends a message
- The message arrives at my handler
- My handler puts the message on a local Queue
- The handler returns

The queue, for each message:
- Calls emit, with Broadcast=True on that message
- SocketIO, does a loop over the clients, emitting it to each client in the room


Now let point out my experimentation results that show something odd is happening:

- In the first case, if I change nothing but the async_handlers to False, my overall throughput goes up. This would indicate the overhead of running the handler in parallel is more than the cost of the handler itself.
- In the Queue case: The handler takes even less time, as the work is given to a separate Queue
- The queue is *not blocking* the handler. This is clearly shown by a setup where two clients are in one room, and a third client is in a different room. The third client still gets maximum throughput, it's only the two clients in the same room that see their throughput drop. But I only have a single Queue, so it can't be causing the bottleneck.
- The same number of calls to emit are being made, with the same number of clients in the room. These potentially always had synchronization overhead, as they are multiple logical threads writing to the same sockets.

Overall I'm not seeing where the queue setup has introduced a problem. I am not preventing any code from running in parallel, and my event handler returns even faster.

**Comment by miguelgrinberg** [comment] 2020-12-02 17:22
It's this one:

| SocketIO, does a loop over the clients, emitting it to each client in the room

In the first case this loop is not serialized, so you can have multiple loops running concurrently. In the second case you are preventing the concurrency so things take a lot longer. The more people in the room the more it will take.

**Comment by mortoray** [comment] 2020-12-02 17:44
But it's not the call to "emit" that is blocking, otherwise in the additional connection case (another room), that client would also be blocked. That is, my call to "emit" is returning quickly. Looking at the code that must mean all the data has been send to the lower-level EngionIO for each connected client already. And that EngineIO send is the same whether I'm running in parallel or not?

If the "emit" was blocking, then my third client would also have the reduced throughput, but it does not. I have only one place I call "emit" at the high-level code, and that's inside my Queue which serves all of the clients/rooms.

**Comment by miguelgrinberg** [comment] 2020-12-02 17:56
I feel I'm unable to make the key point across.

The emit function is asynchronous. You call it, and while it does what it does it reaches points where it blocks, so the CPU goes to other tasks. If you had 100 tasks all doing emit broadcasts at about the same time, these calls will overlap and run in parallel. The 100 calls are not going to run in the same time one broadcast runs, but it'll be much closer to that than to that time multiplied by 100.

When you add the queue, those 100 concurrent tasks are still going to run in parallel, but all they are going to do is put a thing in the queue and return. Then you have a single task that reads those 100 messages from the queue one at a time. So in this case it will take exactly 100 times what it takes to run a single broadcast. These 100 broadcasts are still going to be asynchronous, but while one of the broadcasts is running, the CPU has nothing else to do, because the others are still in the queue waiting to be picked up.

**Comment by mortoray** [comment] 2020-12-02 18:31
I'm sorry, but I don't understand how running emit in parallel is going to improve the sending time, on the assumption that the network send is the slowest operation. Ultimately they all end up at `socket.send` which is doing the work of sending. That call necessarily serializes across all of the threads that are calling it (maybe not immediately, but by the time it reaches the OS socket). And that send call is non-blocking, so it returns immediately.  Having multiple threads in parallel calling "socket.send" shouldn't make that call faster.

I'm not understanding where the load is coming from that parallel processing would speed it up. This should be primarily network bound. If there is a CPU bound operation it's not within the "emit" call, since that is returning quickly, and my queue is clearing quickly.

My CPU is at 100% when I have the slow-down, it is not sitting idle waiting for something.

**Comment by mortoray** [comment] 2020-12-02 18:50
Okay, I did some more targetted timing and it is indeed `emit` that runs slowly. My question is still why? Is there something about the protocol that makes it synchronous with the clients, such that a client sending a message is slower than one who only ever receives?

**Comment by miguelgrinberg** [comment] 2020-12-02 22:58
I don't get what you are saying. I can't answer a question about some test and measurements I have not seen.

**Closed** 2021-04-06 11:41 UTC
Labels: question
