### ISSUE TITLE
Flask_SocketIO (OverFlow) Session if i had any Flask_login or SQLAlchemy commands within any of it's funtions

### ISSUE THREAD

**Issue by ll-M-ll** [miguelgrinberg/Flask-SocketIO#1500] opened 2021-03-18 10:46 UTC
the server breaks with this error within 10-11 refreshes or left it for about 2-5 mins 
(please note: this server is hosted locally for development only and I'm the only user on it, there is not reason for it to get overflow without a fundamental issue.)
`sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)`
followed by this error
`BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call`

 I have this code running on it.
`@socketio.on('custom_emit')

def custom_emit(data):

    if current_user.is_authenticated:  # (**FLASK_LOGIN**)
    
        _id = current_user.get_id() # (**FLASK_LOGIN**)
        
        x = users.query.filter_by(1).first() # (**FLASK_SQLALCHEMY**)
        
        socketio.emit('update_me',{'my_id':x })`
        
        
if I make 5-15 refreshes with this code I get the previously mentioned error

If I removed BOTH  (**FLASK_LOGIN** & **FLASK_SQLALCHEMY**)  from the code and only used regular python or **socketIO** commands , I could spam refreshing as much as I want.

I could use **Flask_SQLALECHMY** with **Flask_Login** together but once **SOCKETIO** is involved, apparently opened sessions doesn't get teardown.

# details on my system's configurations

```
app = Flask(__name__)
app.secret_key= _hidden_
app.config['WTF_CSRF_SECRET_KEY'] = _hidden_


app.config['SQLALCHEMY_DATABASE_URI']=  _hidden_
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)


login = LoginManager(app)
login.init_app(app)


@app.teardown_appcontext
def shutdown_session(exception=None):
    print(f'\n now shutting down request:{db.session} \n')
    db.session.remove()


@login.user_loader
def load_user(n):
    try:
        return users.query.get(int(n))
    except:
        return None

socketio = SocketIO(app, manage_session=False)

if __name__ == "__main__":
    socketio.run(app,debug=True )

```

more details on the errors

```
Traceback (most recent call last):
  File "<hidden_python_directory>\lib\site-packages\eventlet\wsgi.py", line 573, in handle_one_response
    result = self.application(self.environ, start_response)
  File "<hidden_python_directory>\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "<hidden_python_directory>\lib\site-packages\flask_socketio\__init__.py", line 45, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "<hidden_python_directory>\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "<hidden_python_directory>\lib\site-packages\socketio\server.py", line 571, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "<hidden_python_directory>\lib\site-packages\engineio\server.py", line 392, in handle_request
    packets = socket.handle_get_request(
  File "<hidden_python_directory>\lib\site-packages\engineio\socket.py", line 103, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "<hidden_python_directory>\lib\site-packages\engineio\socket.py", line 158, in _upgrade_websocket
    return ws(environ, start_response)
  File "<hidden_python_directory>\lib\site-packages\engineio\async_drivers\eventlet.py", line 20, in __call__
    return super(WebSocketWSGI, self).__call__(environ, start_response)
  File "<hidden_python_directory>\lib\site-packages\eventlet\websocket.py", line 130, in __call__
    self.handler(ws)
  File "<hidden_python_directory>\lib\site-packages\engineio\socket.py", line 184, in _websocket_handler
    pkt = ws.wait()
  File "<hidden_python_directory>\lib\site-packages\eventlet\websocket.py", line 788, in wait
    for i in self.iterator:
  File "<hidden_python_directory>\lib\site-packages\eventlet\websocket.py", line 643, in _iter_frames
    message = self._recv_frame(message=fragmented_message)
  File "<hidden_python_directory>\lib\site-packages\eventlet\websocket.py", line 669, in _recv_frame
    header = recv(2)
  File "<hidden_python_directory>\lib\site-packages\eventlet\websocket.py", line 578, in _get_bytes
    d = self.socket.recv(numbytes - len(data))
  File "<hidden_python_directory>\lib\site-packages\eventlet\greenio\base.py", line 365, in recv
    return self._recv_loop(self.fd.recv, b'', bufsize, flags)
  File "<hidden_python_directory>\lib\site-packages\eventlet\greenio\base.py", line 359, in _recv_loop
    self._read_trampoline()
  File "<hidden_python_directory>\lib\site-packages\eventlet\greenio\base.py", line 327, in _read_trampoline
    self._trampoline(
  File "<hidden_python_directory>\lib\site-packages\eventlet\greenio\base.py", line 208, in _trampoline
    return trampoline(fd, read=read, write=write, timeout=timeout,
  File "<hidden_python_directory>\lib\site-packages\eventlet\hubs\__init__.py", line 159, in trampoline
    return hub.switch()
  File "<hidden_python_directory>\lib\site-packages\eventlet\hubs\hub.py", line 313, in switch
    return self.greenlet.switch()
socket.timeout: timed out

127.0.0.1 - - [12/Mar/2021 13:36:55] "GET /socket.io/?EIO=4&transport=websocket&sid=Wu2Ou1x4dEJnfaynAAAo HTTP/1.1" 500 0 30.117126
Traceback (most recent call last):
  File "<hidden_python_directory>\lib\site-packages\eventlet\wsgi.py", line 573, in handle_one_response
    result = self.application(self.environ, start_response)
  File "<hidden_python_directory>\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "<hidden_python_directory>\lib\site-packages\flask_socketio\__init__.py", line 45, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "<hidden_python_directory>\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "<hidden_python_directory>\lib\site-packages\socketio\server.py", line 571, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "<hidden_python_directory>\lib\site-packages\engineio\server.py", line 392, in handle_request
    packets = socket.handle_get_request(
  File "<hidden_python_directory>\lib\site-packages\engineio\socket.py", line 103, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "<hidden_python_directory>\lib\site-packages\engineio\socket.py", line 158, in _upgrade_websocket
    return ws(environ, start_response)
  File "<hidden_python_directory>\lib\site-packages\engineio\async_drivers\eventlet.py", line 20, in __call__
    return super(WebSocketWSGI, self).__call__(environ, start_response)
  File "<hidden_python_directory>\lib\site-packages\eventlet\websocket.py", line 130, in __call__
    self.handler(ws)
  File "<hidden_python_directory>\lib\site-packages\engineio\socket.py", line 184, in _websocket_handler
    pkt = ws.wait()
  File "<hidden_python_directory>\lib\site-packages\eventlet\websocket.py", line 788, in wait
    for i in self.iterator:
  File "<hidden_python_directory>\lib\site-packages\eventlet\websocket.py", line 643, in _iter_frames
    message = self._recv_frame(message=fragmented_message)
  File "<hidden_python_directory>\lib\site-packages\eventlet\websocket.py", line 669, in _recv_frame
    header = recv(2)
  File "<hidden_python_directory>\lib\site-packages\eventlet\websocket.py", line 578, in _get_bytes
    d = self.socket.recv(numbytes - len(data))
  File "<hidden_python_directory>\lib\site-packages\eventlet\greenio\base.py", line 365, in recv
    return self._recv_loop(self.fd.recv, b'', bufsize, flags)
  File "<hidden_python_directory>\lib\site-packages\eventlet\greenio\base.py", line 359, in _recv_loop
    self._read_trampoline()
  File "<hidden_python_directory>\lib\site-packages\eventlet\greenio\base.py", line 327, in _read_trampoline
    self._trampoline(
  File "<hidden_python_directory>\lib\site-packages\eventlet\greenio\base.py", line 208, in _trampoline
    return trampoline(fd, read=read, write=write, timeout=timeout,
  File "<hidden_python_directory>\lib\site-packages\eventlet\hubs\__init__.py", line 159, in trampoline
    return hub.switch()
  File "<hidden_python_directory>\lib\site-packages\eventlet\hubs\hub.py", line 313, in switch
    return self.greenlet.switch()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<hidden_python_directory>\lib\site-packages\eventlet\wsgi.py", line 357, in __init__
    self.handle()
  File "<hidden_python_directory>\lib\site-packages\eventlet\wsgi.py", line 390, in handle
    self.handle_one_request()
  File "<hidden_python_directory>\lib\site-packages\eventlet\wsgi.py", line 466, in handle_one_request
    self.handle_one_response()
  File "<hidden_python_directory>\lib\site-packages\eventlet\wsgi.py", line 616, in handle_one_response
    write(err_body)
  File "<hidden_python_directory>\lib\site-packages\eventlet\wsgi.py", line 538, in write
    wfile.flush()
  File "<hidden_python_directory>\lib\socket.py", line 722, in write
    return self._sock.send(b)
  File "<hidden_python_directory>\lib\site-packages\eventlet\greenio\base.py", line 396, in send
    return self._send_loop(self.fd.send, data, flags)
  File "<hidden_python_directory>\lib\site-packages\eventlet\greenio\base.py", line 383, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call
```

**Comment by miguelgrinberg** [comment] 2021-03-18 11:23
Try removing your database session when you are done with it:

```python
@socketio.on('custom_emit')
def custom_emit(data):
    if current_user.is_authenticated:
        _id = current_user.get_id()
        x = users.query.filter_by(1).first()
        socketio.emit('update_me',{'my_id':x })
    db.session.remove()
```

**Comment by ll-M-ll** [comment] 2021-03-18 11:27
> Try removing your database session when you are done with it:
> 
> ```python
> @socketio.on('custom_emit')
> def custom_emit(data):
>     if current_user.is_authenticated:
>         _id = current_user.get_id()
>         x = users.query.filter_by(1).first()
>         socketio.emit('update_me',{'my_id':x })
>     db.session.remove()
> ```

Thank you for replying, I did that I even added that on every function I have on the site whether it was a regular routing function it has Flask_SocketIO decorators on it, I got the error every 5-20 refresh

I've also tried to seprate the function from the socketIo function like this.


```
@socketio.on('custom_emit')
def custom_emit(data):
       test()
       ###socketio.emit('update_me',{'my_id':x })


def test():
if current_user.is_authenticated:
        _id = current_user.get_id()
        x = users.query.filter_by(1).first()
```

still, I kept getting overFlow error everytime

**Comment by miguelgrinberg** [comment] 2021-03-18 11:34
Well, the problem is that you are running out of sessions, so my guess is that you are not removing the session correctly.

**Comment by ll-M-ll** [comment] 2021-03-18 12:28
> Well, the problem is that you are running out of sessions, so my guess is that you are not removing the session correctly.

I have the same thought and I've been doing my best to remove the sessions as you can see I've already implemented those lines of code 

```
@app.teardown_appcontext
def shutdown_session(exception=None):
    print(f'\n now shutting down request:{db.session} \n')
    db.session.remove()
```

with print command to make sure that it gets called and yes I can see it being called all the time but still Overflow occurs no matter what only if the socketIO function has any flask_login or Flask_SQLalchemy commands in it.

when i remove them, everything works great and I tested it out, I kept spamming refreshes like crazy, everything seems to be working as they supposed to.

**Comment by miguelgrinberg** [comment] 2021-03-18 12:43
The teardown handler is for Flask routes, it does not run for Socket.IO events. As I said above, you have to manually remove the session in your Socket.IO functions.

**Comment by ll-M-ll** [comment] 2021-03-19 12:38
@

> The teardown handler is for Flask routes, it does not run for Socket.IO events. As I said above, you have to manually remove the session in your Socket.IO functions.

how to do that ? adding `db.session.remove()` didnt help.

**Comment by miguelgrinberg** [comment] 2021-03-19 13:01
You probably did it wrong, or missed one function in which you did not remove the session.

**Comment by ll-M-ll** [comment] 2021-03-19 13:07
> You probably did it wrong, or missed one function in which you did not remove the session.

Well, I've added to the bottom of every function and route code, so you might be right, let me do it again

**Comment by ll-M-ll** [comment] 2021-03-19 13:26
as I've mentions yes `raise exc.TimeoutError(
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)` it still occurring, looks like `db.session.remove()` was not enough and I've added it to every single route ( before `return is called` ) and after `emit` on every **socketIo** function

**Comment by miguelgrinberg** [comment] 2021-03-19 14:21
> also I'm not sure if we should allow socketIO to manage sessions or not

The `manage_session` is about the user session. Your problem is with the database session. They are unrelated.

**Comment by ll-M-ll** [comment] 2021-03-19 14:37
if it helps 

on each update
all those gets called 

```
 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:09] "GET / HTTP/1.1" 200 30459 0.012976
127.0.0.1 - - [19/Mar/2021 16:32:09] "GET /socket.io/?EIO=4&transport=websocket&sid=6z4QQ5r64A-9AemyAAAd HTTP/1.1" 200 0 0.452803
127.0.0.1 - - [19/Mar/2021 16:32:09] "GET /socket.io/?EIO=4&transport=websocket&sid=dR3Wwcry-08UjiOSAAAc HTTP/1.1" 200 0 0.665247

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:09] "GET /static/styles/btss.min.css HTTP/1.1" 200 153709 0.004990

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/styles/main_style.css HTTP/1.1" 200 7512 0.001994

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/styles/oia.min.css HTTP/1.1" 200 59648 0.003998

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/styles/bts.min.css HTTP/1.1" 200 9498 0.001993

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/styles/ac.css HTTP/1.1" 200 3589 0.002983

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/styles/nootd.css HTTP/1.1" 200 4661 0.001993

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/jquery3.6.0.min.js HTTP/1.1" 200 89814 0.002992

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/hhue.min.js HTTP/1.1" 200 80524 0.007978

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/rsst.js HTTP/1.1" 200 1021 0.001996

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/noy.js HTTP/1.1" 200 14561 0.001992

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/dyicForms.js HTTP/1.1" 200 2730 0.008979

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/bts.js HTTP/1.1" 200 260442 0.003988

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/ssdf.min.js HTTP/1.1" 200 307904 0.007980

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/jspdf.plugin.autotable.js HTTP/1.1" 200 15475 0.001994

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/tjs.min.js HTTP/1.1" 200 28582 0.002992

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/tjs.js HTTP/1.1" 200 6655 0.002993

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/aa.js HTTP/1.1" 200 14158 0.004988

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/Autojs/ac.js HTTP/1.1" 200 23863 0.002990

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/Autojs/ac.js HTTP/1.1" 200 7266 0.001995

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/socketio.js HTTP/1.1" 200 6223 0.000997

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/socket.io.3.1.1.min.js HTTP/1.1" 200 61955 0.002991

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/cssfile.js.map HTTP/1.1" 200 316229 0.004987

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 80558 0.003987

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/webfonts/fa-regular-400.woff2 HTTP/1.1" 200 13894 0.001990

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/styles/cssfile.map HTTP/1.1" 200 423776 0.004985

 now shutting down request:<sqlalchemy.orm.scoping.scoped_session object at 0x000001F8E51D8A60>

127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /static/scripts/socket.io.min.js.map HTTP/1.1" 200 157090 0.002991
127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /socket.io/?EIO=4&transport=polling&t=NXAvfj_ HTTP/1.1" 200 277 0.000997
127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /socket.io/?EIO=4&transport=polling&t=NXAvfk2 HTTP/1.1" 200 277 0.001040
(8880) accepted ('127.0.0.1', 49357)
127.0.0.1 - - [19/Mar/2021 16:32:10] "POST /socket.io/?EIO=4&transport=polling&t=NXAvfkw&sid=d865lWZqq4GLK6jnAAAg HTTP/1.1" 200 219 0.000997
127.0.0.1 - - [19/Mar/2021 16:32:10] "GET /socket.io/?EIO=4&transport=polling&t=NXAvfky&sid=d865lWZqq4GLK6jnAAAg HTTP/1.1" 200 181 0.000000
```

**Comment by miguelgrinberg** [comment] 2021-03-19 14:40
I mentioned this in a previous comment:

> The teardown handler is for Flask routes, it does not run for Socket.IO events. As I said above, you have to manually remove the session in your Socket.IO functions.

The teardown thing that you are doing is completely unnecessary, Flask-SQLAlchemy removes the session for you.

**Comment by ll-M-ll** [comment] 2021-03-19 14:43
> I mentioned this in a previous comment:
> 
> > The teardown handler is for Flask routes, it does not run for Socket.IO events. As I said above, you have to manually remove the session in your Socket.IO functions.
> 
> The teardown thing that you are doing is completely unnecessary, Flask-SQLAlchemy removes the session for you at the end of every HTTP request.

ok at least we know now we need to Manually or in anyway remove the sessions that are created by SocketIo as adding `db.session.remove()` to the end of it's functions weren't good enough. I dont know what else I could do.

**Comment by miguelgrinberg** [comment] 2021-03-19 19:04
> that are created by SocketIo

Just to clarify. Socket.IO does not create database sessions, it does not care at all about databases. It's your application that is creating database sessions and not properly closing them.

**Comment by ll-M-ll** [comment] 2021-03-19 19:11
> > that are created by SocketIo
> 
> Just to clarify. Socket.IO does not create database sessions, it does not care at all about databases. It's your application that is creating database sessions and not properly closing them.

but isn't odd that my application closes it under any other function but struggles if it's working with socketIo?
maybe socketIo is using the session in a way that forces Flask_SqlAlchemy to ignore the teardown commands, which results in sessions piles up until they hit the fan.

**Comment by miguelgrinberg** [comment] 2021-03-19 23:43
> maybe socketIo is using the session in a way that forces Flask_SqlAlchemy to ignore the teardown commands

I already explained this. Flask-SocketIO does not use your database session. There is nothing in Flask-SocketIO that requires database use. And also, the teardown handlers are for Flask requests, they are not used at all by Flask-SocketIO and this is by design, since Socket.IO does not have the concept of requests.

To summarize: Flask-SocketIO does not know anything about Flask-SQLAlchemy and Flask-SQLAlchemy does not know anything about Flask-SocketIO. If you use your database session in your Socket.IO handlers, you have to manage the allocation of sessions yourself.

**Comment by ll-M-ll** [comment] 2021-03-20 11:10
> > maybe socketIo is using the session in a way that forces Flask_SqlAlchemy to ignore the teardown commands
> 
> I already explained this. Flask-SocketIO does not use your database session. There is nothing in Flask-SocketIO that requires database use. And also, the teardown handlers are for Flask requests, they are not used at all by Flask-SocketIO and this is by design, since Socket.IO does not have the concept of requests.
> 
> To summarize: Flask-SocketIO does not know anything about Flask-SQLAlchemy and Flask-SQLAlchemy does not know anything about Flask-SocketIO. If you use your database session in your Socket.IO handlers, you have to manage the allocation of sessions yourself.

thank you, that clears things out!.

but I'm not sure how to manage the allocation of the session manually, Is there is any document, tip or any example on how to do that?

**Comment by miguelgrinberg** [comment] 2021-03-20 11:50
I suppose the SQLAlchemy documentation is the reference on this: https://docs.sqlalchemy.org/en/13/orm/session.html.

But it seems we are going back in circles. I already explained that in practice you have to close a session after you use it.

**Comment by ll-M-ll** [comment] 2021-03-20 12:26
> I suppose the SQLAlchemy documentation is the reference on this: https://docs.sqlalchemy.org/en/13/orm/session.html.
> 
> But it seems we are going back in circles. I already explained that in practice you have to close a session after you use it.

I don't think that we are going back in circles because I have already replied to you with feedback on adding  `db.session.remove()` before the return of every function didn't work 
and there is only 1 function that causes this overflow to happen which I've mentioned earlier.

the function currently look like this 
```
@socketio.on('connect_me')
def connect_me(data):
    if current_user.is_authenticated:
        _id = current_user.get_id()
    x = userClass.query.filter_by(id=_id).first()
    db.session.remove()
```
I know the function doesn't make any sense at the moment but I removed the rest of the code just for testing,and still causing overflow. even though I didnt change the database or do anything to with the data I gathered.

so what I'm asking is, If `db.session.remove()` didn't remove the session and didn't fix the problem, what should I try next?

**Comment by miguelgrinberg** [comment] 2021-03-20 12:47
Yes, we are going in circles. I mentioned already that you must have done this incorrectly, or you have other places where sessions are used that you are not removing.

Keep in mind that you have a SQLAlchemy problem. You are asking the maintainer of Flask-SocketIO for a solution. I'm not sure what else you want me to do. This isn't a bug with Flask-SocketIO.

**Comment by ll-M-ll** [comment] 2021-03-20 12:53
@miguelgrinberg  thank you so much 
could you help me explain that to @davidism because originally I've posted the issue on flask_sqlAlchemy but he was so convinced that it's not Flask_SqlALchemy's issue he closed the issue without even looking.
https://github.com/pallets/flask-sqlalchemy/issues/930

**Comment by miguelgrinberg** [comment] 2021-03-20 18:21
It's not an issue with Flask-SQLAlchemy or with SQLAlchemy. It's a bug in your application.

**Comment by ll-M-ll** [comment] 2021-03-20 18:26
> It's not an issue with Flask-SQLAlchemy or with SQLAlchemy. It's a bug in your application.

how so ? I've shared the entire system config. I'm not sure what else I should check, or what i should be looking for?

**Comment by miguelgrinberg** [comment] 2021-03-20 18:41
As I said, I'm not sure what you expect me to do. I explained what the problem is several times already. You are opening database sessions and are not closing them. You can continue to insist this is not your bug, but that is not going to help. What will help is that you accept this fact and look for the function or functions in your application where you are using the database without closing the session. Or close the database session in every single Socket.IO handler if you don't want to go through the effort.

**Closed by miguelgrinberg** 2021-03-20 18:41 UTC
Labels: question

**Comment by ll-M-ll** [comment] 2021-03-20 19:30
I'm using locally hosted postgresql.

> As I said, I'm not sure what you expect me to do. I explained what the problem is several times already. You are opening database sessions and are not closing them. You can continue to insist this is not your bug, but that is not going to help. What will help is that you accept this fact and look for the function or functions in your application where you are using the database without closing the session. Or close the database session in every single Socket.IO handler if you don't want to go through the effort.

first I didnt insist that it's not my bug, I insisted that I don't know how to deal with it and I've followed the instructions and added `db.session.remove()` on every function on the file and still the issue kept occurring., I'm not sure what I should do ?

let me try one more thing, the same file it has two other files imported into it but 1 of them holding the class and other is just for Flask_wtf , but I'll look into them and check if there is anything messing and if it's not I'll try to upload a simple version with 1 function only for you to try it yourself.
