### ISSUE TITLE
Disconnect events don't get triggered on the server when browser page is reloaded or closed

### ISSUE THREAD

**Issue by johaven** [miguelgrinberg/Flask-SocketIO#1280] opened 2020-05-19 16:54 UTC
**Describe the bug**
Disconnect event is correctly triggered when i close properly client connections but not triggered if i refresh the page or close the browser tab.

i checked socketio.server.eio.sockets, the socket is well absent i don't understand why disconnect event was not propagated.

I noticed this because I store the request.sid (append / pop) and for some users i saw 2/3 sids (the disconnect method should have to remove the entries).

**To Reproduce**
Refresh the browser :)

**Expected behavior**
Have a disconnect event when using: **@socketio.on('disconnect')**

**Additional context**
Flask              1.1.2
Flask-SocketIO     4.3.0
python-socketio    4.5.1
uWSGI              2.0.18
gevent             1.4.0

**Comment by miguelgrinberg** [comment] 2020-05-19 17:20
Are your clients using long polling or websocket?

**Comment by johaven** [comment] 2020-05-19 20:33
Websocket

**Comment by miguelgrinberg** [comment] 2020-05-19 22:50
I can't reproduce here. Below is the section of the log in which I did a refresh using the app.py example in this repo:

```
fefc7ec8931049a88bf2cd5c74d9ae5f: Received packet MESSAGE data 2/test,["my_ping"]
fefc7ec8931049a88bf2cd5c74d9ae5f: Sending packet MESSAGE data 2/test,["my_pong"]
[pid: 23702|app: 0|req: 5/4] 127.0.0.1 () {48 vars in 1331 bytes} [Tue May 19 23:49:41 2020] GET / => generated 6026 bytes in 10 msecs (HTTP/1.1 200) 2 headers in 81 bytes (3 switches on core 998)
Client disconnected fefc7ec8931049a88bf2cd5c74d9ae5f
[pid: 23702|app: 0|req: 5/5] 127.0.0.1 () {48 vars in 1462 bytes} [Tue May 19 23:49:21 2020] GET /socket.io/?EIO=3&transport=websocket&sid=fefc7ec8931049a88bf2cd5c74d9ae5f => generated 2140 bytes in 19655 msecs (HTTP/1.1 101) 4 headers in 184 bytes (2 switches on core 999)
8b3ece3c96634438b3c6af36190d0697: Sending packet OPEN data {'sid': '8b3ece3c96634438b3c6af36190d0697', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
```

You can see the `Client disconnected` message printed by this app's disconnect handler.

**Comment by johaven** [comment] 2020-05-20 08:38
I checked your example, it seems to be related to namespaces.

On client side i create two **io** instance (https://socket.io/docs/client-api/#With-multiplexing) like this:
```javascript
const notificationsIOInstance = io('/notifications', {autoConnect: false, reconnection: true, forceNew: false});
const tasksIOInstance = io('/tasks', {autoConnect: false, reconnection: true, forceNew: false});
```
Note: From my understanding there is no need to create an io instance with a namespace '/' this is done automatically and is confirmed in the logs below.

This create an unique websocket with multiple namespaces (multiplexing).

To debug i created 3 listeners on server side, until now i used only one disconnect handler (DISCONNECT 0)
```python
@socketio.on('connect')
def socket_connect():
    print('sockets', socketio.server.eio.sockets)
    print('namespace', request.namespace)
    UserStatus.set_user_as_online(g.user, request.sid)
    return True


@socketio.on('disconnect')
def socket_disconnect():
    print('DISCONNECT 0')
    UserStatus.set_user_as_offline(g.user, request.sid)
    return True


@socketio.on('disconnect', namespace='/tasks')
def socket_disconnect1():
    print('DISCONNECT 1')
    return True


@socketio.on('disconnect', namespace='/notifications')
def socket_disconnect2():
    print('DISCONNECT 2')
    return True
```

**On connection**
```
e871e227b6444af7a39651472403abb9: Sending packet OPEN data {'sid': 'e871e227b6444af7a39651472403abb9', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
sockets {'e871e227b6444af7a39651472403abb9': <engineio.socket.Socket object at 0x1139aaf50>}
namespace /
[2020-05-20 10:25:56,977] DEBUG (manager.py:44): *User jo 1* is online
[2020-05-20 10:25:56,977] DEBUG (manager.py:52): current users online: {1: ['e871e227b6444af7a39651472403abb9']}
e871e227b6444af7a39651472403abb9: Sending packet MESSAGE data 0
e871e227b6444af7a39651472403abb9: Received packet MESSAGE data 0/tasks,
e871e227b6444af7a39651472403abb9: Sending packet MESSAGE data 0/tasks
e871e227b6444af7a39651472403abb9: Received request to upgrade to websocket
e871e227b6444af7a39651472403abb9: Received packet MESSAGE data 0/notifications,
e871e227b6444af7a39651472403abb9: Sending packet MESSAGE data 0/notifications
e871e227b6444af7a39651472403abb9: Upgrade to websocket successful
e871e227b6444af7a39651472403abb9: Received packet PING data None
e871e227b6444af7a39651472403abb9: Sending packet PONG data None
```

**Manually disconnect (all disconnects handler has been called on server side)**
```javascript
notificationsIOInstance.disconnect()
tasksIOInstance.disconnect()
```
```
e871e227b6444af7a39651472403abb9: Received packet MESSAGE data 1/tasks,
DISCONNECT 1
127.0.0.1:5000 [pid: 1435|app: 0|req: 37/36] 127.0.0.1 () {50 vars in 2048 bytes} [Wed May 20 10:27:55 2020] POST /auth/logout => generated 3 bytes in 0 msecs (HTTP/1.1 200) 7 headers in 485 bytes (3 switches on core 249)
e871e227b6444af7a39651472403abb9: Received packet MESSAGE data 1/notifications,
DISCONNECT 2
DISCONNECT 0
```

**Closing Browser Tab or reloading page (only namespaced handlers are called)**
```
DISCONNECT 1
DISCONNECT 2
127.0.0.1:5000 [pid: 1456|app: 0|req: 37/37] 127.0.0.1 () {52 vars in 2193 bytes} [Wed May 20 10:29:37 2020] GET /socket.io/?EIO=3&transport=websocket&sid=c7ad72fc62be4fd9af35a42ad370c8ed => generated 36 bytes in 35606 msecs (HTTP/1.1 101) 5 headers in 208 bytes (2 switches on core 244)
```

The default namespace handler was never called except if we disconnect the client instances properly

**Comment by johaven** [comment] 2020-05-20 10:14
I printed socketio/server.py (line 646):

```python
    def _handle_disconnect(self, sid, namespace):
        """Handle a client disconnect."""
        print('TEST', sid, namespace)
```

it's interesting because the disconnect event are correctly handled on namespace '/' :
```
TEST 59f457660f254dd2bd6f9733bcf82996 /
DISCONNECT 1
DISCONNECT 2
```
```python
namespace_list = ['/', '/tasks', '/notifications']
```
Namespace list is correct
```
        if namespace == '/' and self.manager.is_connected(sid, namespace):
            print(2)
            self.manager.pre_disconnect(sid, namespace=namespace)
            self._trigger_event('disconnect', '/', sid)
            self.manager.disconnect(sid, '/')
```
But we do not enter in this part of code (socketio/server.py (line 660):
```python
        if namespace == '/' and self.manager.is_connected(sid, namespace):
            self.manager.pre_disconnect(sid, namespace=namespace)
            self._trigger_event('disconnect', '/', sid)
            self.manager.disconnect(sid, '/')
```
because _self.manager.is_connected(sid, namespace)_ return False

**Comment by miguelgrinberg** [comment] 2020-05-20 10:24
Thanks for all the additional details, I'll look into it.

**Comment by johaven** [comment] 2020-05-20 10:25
if i check _self.manager.is_connected_ in socketio/base_manager.py (line 48) and printing _self.pending_disconnect_
```python
PENDING {}
DISCONNECT 1
PENDING {'/': ['8e53dfc8caf04cd4935c2faa0a8672a2']}
DISCONNECT 2
PENDING {'/': ['8e53dfc8caf04cd4935c2faa0a8672a2', '8e53dfc8caf04cd4935c2faa0a8672a2']}
```
Namespace '/' has state _pending disconnect_ when first namespace was disconnected.

If i do connection and disconnection manually, pending seems to be appended every time:
```python
PENDING {'/': ['8e53dfc8caf04cd4935c2faa0a8672a2', '8e53dfc8caf04cd4935c2faa0a8672a2']}
DISCONNECT 1
127.0.0.1:5000 [pid: 1964|app: 0|req: 35/34] 127.0.0.1 () {46 vars in 1995 bytes} [Wed May 20 12:23:26 2020] POST /auth/logout => generated 3 bytes in 0 msecs (HTTP/1.1 200) 7 headers in 485 bytes (3 switches on core 245)
PENDING {'/': ['8e53dfc8caf04cd4935c2faa0a8672a2', '8e53dfc8caf04cd4935c2faa0a8672a2']}
DISCONNECT 2
PENDING {'/': ['8e53dfc8caf04cd4935c2faa0a8672a2', '8e53dfc8caf04cd4935c2faa0a8672a2', 'fedc440447a441369906e59776c718f3']}
```

**Comment by miguelgrinberg** [comment] 2020-05-22 22:29
I spent some time today trying to reproduce this issue without success. It appears you were using uwsgi as browser so I used the same. I tested explicit disconnects of the two namespaces, closing the tab and refreshing it. In all cases the root namespace's disconnect handler was called after the two active namespaces were disconnected.

So I'm really at a loss. If you want to provide complete source code that demonstrates the issue I'll be happy to continue debugging, but so far I don't see any problem.

**Comment by johaven** [comment] 2020-05-23 09:17
I took the example application from this repository.

I installed gevent, gevent-websocket, i added a connect and disconnect handler for main namespace.

Started app with = `FLASK_ENV=development python3 app.py`, i observe the same behavior when reloading page or closing tab the disconnect handler from the main namespace is never called.
```
Client connected on main 722da6fafa5c4dcfbd69eae91ad1487c
Client connected on test 722da6fafa5c4dcfbd69eae91ad1487c
Client disconnected from test 722da6fafa5c4dcfbd69eae91ad1487c
Client connected on main dd6ce459fc02433fa6be3786047dc684
Client connected on test dd6ce459fc02433fa6be3786047dc684
Client disconnected from test dd6ce459fc02433fa6be3786047dc684
Client connected on main 95d678c4a15441139821170d16861de2
Client connected on test 95d678c4a15441139821170d16861de2
```
[Debug.zip](https://github.com/miguelgrinberg/Flask-SocketIO/files/4671449/Debug.zip)

**Comment by johaven** [comment] 2020-05-24 19:20
Did you observe the same behaviour ?

**Comment by miguelgrinberg** [comment] 2020-05-25 10:50
Below is the output from your application. I loaded the app, refreshed the page three times, then closed the tab.

```
(venv) Debug $ python app.py
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 225-751-490
Client connected on main 0c376fdf781e4b8892fcb7f92292dd97
Client connected on test 0c376fdf781e4b8892fcb7f92292dd97
Client disconnected from test 0c376fdf781e4b8892fcb7f92292dd97
Client disconnected from main 0c376fdf781e4b8892fcb7f92292dd97
Client connected on main 8555eb8bd28b45d08c1f7d7ab3b4bf96
Client connected on test 8555eb8bd28b45d08c1f7d7ab3b4bf96
Client disconnected from test 8555eb8bd28b45d08c1f7d7ab3b4bf96
Client disconnected from main 8555eb8bd28b45d08c1f7d7ab3b4bf96
Client connected on main 9d4b9ff9a35845a1b9908cf3ecce4ef9
Client connected on test 9d4b9ff9a35845a1b9908cf3ecce4ef9
Client disconnected from test 9d4b9ff9a35845a1b9908cf3ecce4ef9
Client disconnected from main 9d4b9ff9a35845a1b9908cf3ecce4ef9
Client connected on main 7d5e561a6b69489f865a8d1553e7dd15
Client connected on test 7d5e561a6b69489f865a8d1553e7dd15
Client disconnected from test 7d5e561a6b69489f865a8d1553e7dd15
Client disconnected from main 7d5e561a6b69489f865a8d1553e7dd15
```

I can't really explain your issue, unless you are using an older version of either python-socketio or python-engineio. There's been bugs at different times that caused connect or disconnect handlers to not being invoked, but as far as I know everything is correct now.

**Comment by johaven** [comment] 2020-05-25 11:15
Did you use the same requirements.txt from zip ?

What is your Python version ?

**Comment by miguelgrinberg** [comment] 2020-05-25 11:27
I've made a new venv from the requirements.txt file in your package.

**Comment by johaven** [comment] 2020-05-25 11:53
it's really curious because i used a venv too ...

Just to be sure can you paste me the output of the pip freeze?

**Comment by miguelgrinberg** [comment] 2020-05-25 11:56
```
click==7.1.2
Flask==1.0.2
Flask-Login==0.4.1
Flask-Session==0.3.1
Flask-SocketIO==4.3.0
gevent==20.5.0
gevent-websocket==0.10.1
greenlet==0.4.15
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.0
python-engineio==3.13.0
python-socketio==4.6.0
six==1.11.0
Werkzeug==0.14.1
```

**Comment by johaven** [comment] 2020-05-25 12:13
The bug is present in python-socketio==4.5.1.

You updated 2 days ago to 4.6.0, and now it's ok.

**Closed** 2020-05-25 12:15 UTC
Labels: question
